<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <OutputType>Library</OutputType>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <UseWPF>true</UseWPF>
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
        <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <OutputPath>..\bin\Debug\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <DebugType>embedded</DebugType>
        <OutputPath>..\bin\Release\</OutputPath>
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="JetBrains.Annotations">
            <HintPath>..\..\..\..\.nuget\packages\jetbrains.annotations\2024.3.0\lib\net20\JetBrains.Annotations.dll</HintPath>
        </Reference>
        <Reference Include="PresentationCore" />
        <Reference Include="PresentationFramework" />
        <Reference Include="System" />
        <Reference Include="System.Core" />
        <Reference Include="System.Xml.Linq" />
        <Reference Include="System.Data.DataSetExtensions" />
        <Reference Include="Microsoft.CSharp" />
        <Reference Include="System.Data" />
        <Reference Include="System.Net.Http" />
        <Reference Include="System.Xml" />
        <Reference Include="WindowsBase" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\BgsService\EddiBgsService.csproj" />
        <ProjectReference Include="..\CompanionAppService\EddiCompanionAppService.csproj" />
        <ProjectReference Include="..\ConfigService\EddiConfigService.csproj" />
        <ProjectReference Include="..\DataDefinitions\EddiDataDefinitions.csproj" />
        <ProjectReference Include="..\DataProviderService\EddiDataProviderService.csproj" />
        <ProjectReference Include="..\EddiSpanshService\EddiSpanshService.csproj" />
        <ProjectReference Include="..\EddiStatusService\EddiStatusService.csproj" />
        <ProjectReference Include="..\Events\EddiEvents.csproj" />
        <ProjectReference Include="..\SpeechService\EddiSpeechService.csproj" />
        <ProjectReference Include="..\StarMapService\EddiStarMapService.csproj" />
        <ProjectReference Include="..\Utilities\Utilities.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>
    <ItemGroup>
      <Compile Update="Properties\EddiResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>EddiResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Properties\MainWindow.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>MainWindow.resx</DependentUpon>
      </Compile>
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Update="Properties\EddiResources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>EddiResources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Properties\MainWindow.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>MainWindow.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
</Project>