<Project>

	<!-- Set our source revision ID equal to our latest git commit ID -->
	<Target Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
		<Exec Command="git rev-parse HEAD" ConsoleToMSBuild="True" IgnoreExitCode="True">
			<Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput" />
		</Exec>
		<ItemGroup>
			<AssemblyMetadata Include="SourceRevisionId" Value="$(SourceRevisionId)" />
		</ItemGroup>
	</Target>

	<!-- Set our source branch -->
	<Target Name="SetSourceBranch" BeforeTargets="InitializeSourceControlInformation">
		<Exec Command="git rev-parse --abbrev-ref HEAD" ConsoleToMSBuild="True" IgnoreExitCode="True">
			<Output PropertyName="SourceBranch" TaskParameter="ConsoleOutput" />
		</Exec>
		<ItemGroup>
			<AssemblyMetadata Include="SourceBranch" Value="$(SourceBranch)" />
		</ItemGroup>
	</Target>

    <!-- Import injected credentials -->
    <Import Project="build\InjectedSecrets.targets" Condition="Exists('build\InjectedSecrets.targets')" />

    <Target Name="SetPublicResxSourceGeneration"
            BeforeTargets="AddAllResxFilesAsAdditionalFiles;AddGenerateSourceResxFilesAsAdditionalFiles">
        <ItemGroup>
            <EmbeddedResource Update="@(EmbeddedResource)"
                              Public="true"
                              Condition="'%(EmbeddedResource.Generator)' == 'PublicResXFileCodeGenerator'" />
            <EmbeddedResource Update="@(EmbeddedResource)"
                              ClassName="$(EddiRootNamespace).$([System.String]::Copy('%(EmbeddedResource.RelativeDir)').Replace('\', '.').Replace('/', '.'))$([System.String]::Copy('%(EmbeddedResource.LastGenOutput)').Replace('.Designer.cs', '').Replace('.', '_'))"
                              Condition="'%(EmbeddedResource.LastGenOutput)' != ''" />
        </ItemGroup>
    </Target>

    <ItemGroup>
        <_SourceGeneratedResxDesigner Include="@(EmbeddedResource->'%(RelativeDir)%(LastGenOutput)')" />
        <_SourceGeneratedResxDesigner Include="@(EmbeddedResource->'%(RootDir)%(Directory)%(LastGenOutput)')" />
        <_SourceGeneratedResxDesigner Remove="@(_SourceGeneratedResxDesigner->WithMetadataValue('GenerateSource', 'false'))" />
        <Compile Remove="@(_SourceGeneratedResxDesigner)" />
    </ItemGroup>

    <Target Name="RemoveSourceGeneratedResxDesignerFiles"
            BeforeTargets="CoreCompile">
        <ItemGroup>
            <Compile Remove="@(_SourceGeneratedResxDesigner)" />
        </ItemGroup>
    </Target>
</Project>
