<Project>

    <PropertyGroup>

        <!-- Targeting and Output -->
        <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
        <Platforms>x64</Platforms>

        <!-- Auto-generate AssemblyInfo.cs -->
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>

        <!-- Normalize embedded stacktrace paths, make them relative rather than absolute -->
        <PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>

        <!-- Don't append the target framework, runtime identifier, or platform to the output path -->
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>

    </PropertyGroup>

    <!-- Ensure projects which use WPF or Windows Forms import Windows Desktop targets -->
    <PropertyGroup Condition="'$(UseWPF)' == 'true' or '$(UseWindowsForms)' == 'true'">
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">

        <!-- Always include embedded debug symbols in our Release builds -->
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>

    </PropertyGroup>

	<!-- Set up localization to fallback to the main assembly and en neutral language -->
	<ItemGroup>
		<AssemblyAttribute Include="System.Resources.NeutralResourcesLanguageAttribute">
			<_Parameter1>en</_Parameter1>
			<_Parameter2>MainAssembly</_Parameter2>
		</AssemblyAttribute>
	</ItemGroup>

</Project>