; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EDDI"
#define MyAppVersion "5.0.1"
#define MyAppPublisher "Elite Dangerous Community Developers (EDCD)"
#define MyAppURL "https://github.com/EDCD/EDDI/"
#define MyAppExeName "EDDI.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AllowUNCPath=no
AppId={{830C0324-30D8-423C-B5B4-D7EE8D007A79}
AppName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppVerName={#MyAppName} {#MyAppVersion}
AppVersion={#MyAppVersion}
CloseApplications=yes
DefaultDirName={code:GetDefaultInstallDir}
DefaultGroupName={#MyAppName}
DirExistsWarning=no
DisableDirPage=no
DisableWelcomePage=no
LicenseFile="{#SourcePath}\LicenseFile.txt"
OutputBaseFilename={#MyAppName}-{#MyAppVersion}
OutputDir="{#SourcePath}\bin\Installer"
RestartApplications=no
SolidCompression=yes
SourceDir="{#SourcePath}\bin\Release"
UninstallDisplayIcon={app}\{#MyAppExeName}
UsePreviousAppDir=no
UsePreviousTasks=no
WizardImageFile={#SourcePath}\graphics\logo.bmp
WizardSmallImageFile={#SourcePath}\graphics\logo.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "*.exe"; DestDir: "{app}"
Source: "*.exe.config"; DestDir: "{app}"; Flags: skipifsourcedoesntexist

Source: "runtimes\*.*"; DestDir: "{app}\runtimes"; Flags: recursesubdirs createallsubdirs

Source: "*.dll"; DestDir: "{app}"; Excludes: "Tests.dll"
Source: "*.dll.config"; DestDir: "{app}"; Flags: skipifsourcedoesntexist

Source: "*.resources.dll"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs
Source: "eddi.json"; DestDir: "{app}"
Source: "eddi.*.json"; DestDir: "{app}"
Source: "*.md"; DestDir: "{app}"
Source: "*.vap"; DestDir: "{app}"

; Remove outdated files
[InstallDelete]
; --- Remove old architecture folders entirely ---
Type: filesandordirs; Name: "{app}\x86"
Type: filesandordirs; Name: "{app}\x64"
Type: filesandordirs; Name: "{app}\runtimes"

; --- Remove all old DLLs in the root folder ---
Type: files; Name: "{app}\*.dll"

; --- Remove old PDBs ---
Type: files; Name: "{app}\*.pdb"

; --- Remove old doc files ---
Type: files; Name: "{app}\*.md"
Type: files; Name: "{app}\*.xml"

; --- Remove old default personality files ---
Type: files; Name: "{app}\eddi.json"
Type: files; Name: "{app}\eddi.*.json"

; --- Remove old VoiceAttack profiles ---
Type: files; Name: "{app}\*.vap"

; --- Remove old resource files that may no longer be valid ---
Type: filesandordirs; Name: "{app}\*\*.resources.dll"

; --- Remove old config files that may no longer be valid ---
Type: files; Name: "{app}\*.dll.config"

; --- Remove old user-specific cached configs that cause runtime mismatches ---
Type: filesandordirs; Name: "{localappdata}\Eddi\Eddi.exe_*"
Type: files; Name: "{localappdata}\Eddi\Eddi.exe_*\*\user.config"

; --- Remove obsolete legacy files from older EDDI versions ---
Type: files; Name: "{app}\*.exe"
Type: files; Name: "{app}\*.exe.config"
Type: files; Name: "{app}\EDDI.ico"
Type: files; Name: "{userappdata}\EDDI\credentials.json"
Type: files; Name: "{userappdata}\EDDI\elite.json"
Type: filesandordirs; Name: "{userappdata}\EDDI\galnet"

; Remove sensitive data on uninstall
[UninstallDelete]
Type: files; Name: "{userappdata}\EDDI\CompanionAPI.json"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[ThirdParty]
UseRelativePaths=True

[Messages]
SelectDirBrowseLabel=To continue, click Next. If this is not your VoiceAttack 2 installation location, or you would like to put the EDDI files in a different location, click Browse.

[Registry]
Root: "HKLM"; Subkey: "Software\Classes\eddi"; ValueType: string; ValueData: "EDDI URL Protocol"; Flags: uninsdeletekey
Root: "HKLM"; Subkey: "Software\Classes\eddi"; ValueType: string; ValueName: "URL Protocol"; Flags: uninsdeletekey
Root: "HKLM"; Subkey: "Software\Classes\eddi\Default Icon"; ValueType: string; ValueData: "{app}\{#MyAppExeName},0"; Flags: uninsdeletekey
Root: "HKLM"; Subkey: "Software\Classes\eddi\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey
Root: "HKLM"; Subkey: "Software\Classes\eddi\shell\open\ddeexec"; ValueType: string; ValueData: "%1"; Flags: uninsdeletekey
Root: "HKCU"; Subkey: "Software\Classes\eddi"; ValueType: string; ValueData: "EDDI URL Protocol"; Flags: uninsdeletekey
Root: "HKCU"; Subkey: "Software\Classes\eddi"; ValueType: string; ValueName: "URL Protocol"; Flags: uninsdeletekey
Root: "HKCU"; Subkey: "Software\Classes\eddi\Default Icon"; ValueType: string; ValueData: "{app}\{#MyAppExeName},0"; Flags: uninsdeletekey
Root: "HKCU"; Subkey: "Software\Classes\eddi\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey
Root: "HKCU"; Subkey: "Software\Classes\eddi\shell\open\ddeexec"; ValueType: string; ValueData: "%1"; Flags: uninsdeletekey

[Code]

function NormalizePath(const S: string): string;
begin
  Result := Lowercase(RemoveBackslashUnlessRoot(S));
end;

function SamePath(const A, B: string): Boolean;
begin
  Result := NormalizePath(A) = NormalizePath(B);
end;

function IsUnderPath(const Child, Parent: string): Boolean;
var
  C, P: string;
begin
  C := NormalizePath(Child);
  P := NormalizePath(Parent);
  Result := (C = P) or (Pos(P + '\', C) = 1);
end;

function TryGetVoiceAttack2AppsDir(var Dir: string): Boolean;
var
  VAFolder: string;
begin
  Result := False;

  if RegQueryStringValue(
       HKCU,
       'Software\VoiceAttack.com\VoiceAttack2\LastRun',
       'AppsFolder',
       Dir) and (Trim(Dir) <> '') then
  begin
    Dir := RemoveBackslashUnlessRoot(Dir);
    Result := True;
    exit;
  end;

  if RegQueryStringValue(
       HKCU,
       'Software\VoiceAttack.com\VoiceAttack2\LastRun',
       'VAFolder',
       VAFolder) and (Trim(VAFolder) <> '') then
  begin
    Dir := AddBackslash(RemoveBackslashUnlessRoot(VAFolder)) + 'Apps';
    Result := True;
  end;
end;

function GetDefaultInstallDir(Param: string): string;
var
  AppsFolder: string;
begin
  if TryGetVoiceAttack2AppsDir(AppsFolder) then
  begin
    Result := AddBackslash(RemoveBackslashUnlessRoot(AppsFolder)) + '{#MyAppName}';
    exit;
  end;

  Result := ExpandConstant('{userappdata}\VoiceAttack2\Apps\{#MyAppName}');
end;

function GetPreviousEddiInstallDir: string;
begin
  Result := '';

  RegQueryStringValue(
    HKLM,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{830C0324-30D8-423C-B5B4-D7EE8D007A79}_is1',
    'InstallLocation',
    Result);

  if Trim(Result) <> '' then
    Result := RemoveBackslashUnlessRoot(Result);
end;

function TryGetLegacyVoiceAttackAppsDir(var Dir: string): Boolean;
var
  VAFolder: string;
begin
  Result := False;

  if RegQueryStringValue(
       HKCU,
       'Software\VoiceAttack.com\VoiceAttack\LastRun',
       'AppsFolder',
       Dir) and (Trim(Dir) <> '') then
  begin
    Dir := RemoveBackslashUnlessRoot(Dir);
    Result := True;
    exit;
  end;

  if RegQueryStringValue(
       HKCU,
       'Software\VoiceAttack.com\VoiceAttack\LastRun',
       'VAFolder',
       VAFolder) and (Trim(VAFolder) <> '') then
  begin
    Dir := AddBackslash(RemoveBackslashUnlessRoot(VAFolder)) + 'Apps';
    Result := True;
  end;
end;

function GetLegacyEddiDir: string;
var
  LegacyAppsDir: string;
begin
  Result := '';

  if TryGetLegacyVoiceAttackAppsDir(LegacyAppsDir) then
    Result := AddBackslash(RemoveBackslashUnlessRoot(LegacyAppsDir)) + '{#MyAppName}';
end;

function IsLegacyVoiceAttackPath(const Dir: string): Boolean;
var
  LegacyAppsDir: string;
  VoiceAttack2AppsDir: string;
begin
  Result := False;

  if not TryGetLegacyVoiceAttackAppsDir(LegacyAppsDir) then
    exit;

  {
    VoiceAttack supports an in-place v1 -> v2 upgrade. In that case both
    registry hives can legitimately point to the same Apps folder. Do not
    block the selected path as legacy when the v1 and v2 Apps folders match.
  }
  if TryGetVoiceAttack2AppsDir(VoiceAttack2AppsDir) and
     SamePath(LegacyAppsDir, VoiceAttack2AppsDir) then
  begin
    Log(Format(
      'VoiceAttack and VoiceAttack 2 are registered to the same Apps folder: "%s".',[LegacyAppsDir]));
    exit;
  end;

  Result := IsUnderPath(Dir, LegacyAppsDir);
end;

procedure RegisterCloseResource(const Dir: string);
var
  ExePath: string;
begin
  if Trim(Dir) = '' then
    exit;

  ExePath := AddBackslash(RemoveBackslashUnlessRoot(Dir)) + '{#MyAppExeName}';

  if FileExists(ExePath) then
    RegisterExtraCloseApplicationsResource(False, ExePath);
end;

procedure RegisterExtraCloseApplicationsResources;
begin
  RegisterCloseResource(GetLegacyEddiDir);
  RegisterCloseResource(GetPreviousEddiInstallDir);
end;

function RemoveDirIfOldEddiInstall(const Dir: string): Boolean;
var
  CleanDir: string;
begin
  Result := True;

  if Trim(Dir) = '' then
    exit;

  CleanDir := RemoveBackslashUnlessRoot(Dir);

  if not DirExists(CleanDir) then
    exit;

  if SamePath(CleanDir, ExpandConstant('{app}')) then
    exit;

  if FileExists(AddBackslash(CleanDir) + '{#MyAppExeName}') then
  begin
    Log(Format('Removing old EDDI install at "%s".', [CleanDir]));
    Result := DelTree(CleanDir, True, True, True);
  end;
end;

function RemoveOldEddiInstalls: Boolean;
begin
  Result :=
    RemoveDirIfOldEddiInstall(GetLegacyEddiDir) and
    RemoveDirIfOldEddiInstall(GetPreviousEddiInstallDir);
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ChosenDir: string;
begin
  Result := True;

  if CurPageID = wpSelectDir then
  begin
    ChosenDir := RemoveBackslashUnlessRoot(WizardDirValue);

    if IsLegacyVoiceAttackPath(ChosenDir) then
    begin
      MsgBox(
        'Installing EDDI into the legacy VoiceAttack plugin location is no longer supported.' + #13#10#13#10 +
        'Select the new VoiceAttack 2 Apps folder instead.',
        mbError, MB_OK);
      Result := False;
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    if not RemoveOldEddiInstalls then
    begin
      MsgBox(
        'Setup could not remove an old EDDI install.' + #13#10#13#10 +
        'Close EDDI and VoiceAttack, then run Setup again.',
        mbCriticalError, MB_OK);
      Abort;
    end;
  end;
end;
