<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <UseWPF>true</UseWPF>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <UserSecretsId>bbc0edf6-4284-46b2-9993-f59e2097c3b1</UserSecretsId>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
        <OutputPath>..\bin\Debug\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
        <OutputPath>..\bin\Release\</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="MathNet.Numerics" />
        <PackageReference Include="Microsoft.CSharp" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="Rollbar" />
        <PackageReference Include="System.Collections" />
        <PackageReference Include="System.Diagnostics.Debug" />
        <PackageReference Include="System.Linq" />
        <PackageReference Include="System.Linq.Expressions" />
        <PackageReference Include="System.ObjectModel" />
        <PackageReference Include="System.Reflection" />
        <PackageReference Include="System.Reflection.Extensions" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Properties\IPA.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>IPA.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Properties\IPA.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>IPA.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
</Project>
