<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <UseWPF>true</UseWPF>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
        <OutputPath>..\bin\Debug\Application\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
        <OutputPath>..\bin\Release\Application\</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Utilities\Utilities.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.CSharp" />
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Properties\CapiResources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>CapiResources.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Properties\CapiResources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>CapiResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
</Project>
