<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <!--Dynamic loading copies dependencies of dynamically loaded assemblies to the output directory-->
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\bin\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CompanionAppService\EddiCompanionAppService.csproj" />
    <ProjectReference Include="..\DataDefinitions\EddiDataDefinitions.csproj" />
    <ProjectReference Include="..\EddiCore\EddiCore.csproj" />
    <ProjectReference Include="..\Events\EddiEvents.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Runtime" />
    <PackageReference Include="System.Runtime.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\EddnResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EddnResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\EddnResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EddnResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>