//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Abasheli_Barracks {
            get {
                object obj = ResourceManager.GetObject("Abasheli_Barracks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bgsFaction {
            get {
                object obj = ResourceManager.GetObject("bgsFaction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bgsFactionResponse {
            get {
                object obj = ResourceManager.GetObject("bgsFactionResponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CapitalSystems {
            get {
                object obj = ResourceManager.GetObject("CapitalSystems", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] cubeSystemsAroundSol {
            get {
                object obj = ResourceManager.GetObject("cubeSystemsAroundSol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] edsmBodies {
            get {
                object obj = ResourceManager.GetObject("edsmBodies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] edsmDeaths {
            get {
                object obj = ResourceManager.GetObject("edsmDeaths", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] edsmFactions {
            get {
                object obj = ResourceManager.GetObject("edsmFactions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] edsmStations {
            get {
                object obj = ResourceManager.GetObject("edsmStations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] edsmSystem {
            get {
                object obj = ResourceManager.GetObject("edsmSystem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] edsmTraffic {
            get {
                object obj = ResourceManager.GetObject("edsmTraffic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fighterLoadout {
            get {
                object obj = ResourceManager.GetObject("fighterLoadout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] loadout {
            get {
                object obj = ResourceManager.GetObject("loadout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] shipMonitor {
            get {
                object obj = ResourceManager.GetObject("shipMonitor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Sol {
            get {
                object obj = ResourceManager.GetObject("Sol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SolBodies {
            get {
                object obj = ResourceManager.GetObject("SolBodies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SolFactions {
            get {
                object obj = ResourceManager.GetObject("SolFactions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SolStations {
            get {
                object obj = ResourceManager.GetObject("SolStations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sphereAroundSol {
            get {
                object obj = ResourceManager.GetObject("sphereAroundSol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sqlStarSystem1 {
            get {
                object obj = ResourceManager.GetObject("sqlStarSystem1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sqlStarSystem2 {
            get {
                object obj = ResourceManager.GetObject("sqlStarSystem2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sqlStarSystem3 {
            get {
                object obj = ResourceManager.GetObject("sqlStarSystem3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sqlStarSystem4 {
            get {
                object obj = ResourceManager.GetObject("sqlStarSystem4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * tet02 Orionis C
        ///1 Aurigae
        ///1 Epsilon Equulei
        ///1 G. Caeli
        ///1 Geminorum
        ///1 Hydrae
        ///1 Kappa Cygni
        ///1 M Serpentis
        ///1 Omicron Tauri
        ///1 Pegasi
        ///1 b Scorpii
        ///1 i Centauri
        ///10 Arietis
        ///10 Canum Venaticorum
        ///10 Comae Berenices
        ///10 Delta Coronae Borealis
        ///10 G. Canis Majoris
        ///10 Hydrae
        ///10 Iota Cygni
        ///10 Kappa Pegasi
        ///10 Lacertae
        ///10 Omega-2 Scorpii
        ///10 Rho-3 Eridani
        ///10 Serpentis
        ///10 Tauri
        ///10 Theta Piscium
        ///10 Ursae Majoris
        ///101 Aquarii
        ///101 Herculis
        ///101 Tauri
        ///102 Pi Piscium
        ///103 G. Capricorni
        ///105 Piscium
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string starsystems {
            get {
                return ResourceManager.GetString("starsystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] vehicle {
            get {
                object obj = ResourceManager.GetObject("vehicle", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
