//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiNavigationMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NavigationMonitor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavigationMonitor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiNavigationMonitor.Properties.NavigationMonitor", typeof(NavigationMonitor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark.
        /// </summary>
        public static string add_button {
            get {
                return ResourceManager.GetString("add_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Bookmarks.
        /// </summary>
        public static string bm_export_button {
            get {
                return ResourceManager.GetString("bm_export_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export bookmarks from .csv file.
        /// </summary>
        public static string bm_export_button_tooltip {
            get {
                return ResourceManager.GetString("bm_export_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Bookmarks.
        /// </summary>
        public static string bm_import_button {
            get {
                return ResourceManager.GetString("bm_import_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import bookmarks from .csv file.
        /// </summary>
        public static string bm_import_button_tooltip {
            get {
                return ResourceManager.GetString("bm_import_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark Location.
        /// </summary>
        public static string bm_location_button {
            get {
                return ResourceManager.GetString("bm_location_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bookmark for current location.
        /// </summary>
        public static string bm_location_button_tooltip {
            get {
                return ResourceManager.GetString("bm_location_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bookmark.
        /// </summary>
        public static string bm_query_button {
            get {
                return ResourceManager.GetString("bm_query_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bookmark from query results.
        /// </summary>
        public static string bm_query_button_tooltip {
            get {
                return ResourceManager.GetString("bm_query_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string find_text {
            get {
                return ResourceManager.GetString("find_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string header_body {
            get {
                return ResourceManager.GetString("header_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string header_comment {
            get {
                return ResourceManager.GetString("header_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string header_latitude {
            get {
                return ResourceManager.GetString("header_latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string header_longitude {
            get {
                return ResourceManager.GetString("header_longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI.
        /// </summary>
        public static string header_poi {
            get {
                return ResourceManager.GetString("header_poi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string header_system {
            get {
                return ResourceManager.GetString("header_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform navigation queries, make and use bookmarks.
        /// </summary>
        public static string navigation_monitor_desc {
            get {
                return ResourceManager.GetString("navigation_monitor_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Monitor.
        /// </summary>
        public static string navigation_monitor_name {
            get {
                return ResourceManager.GetString("navigation_monitor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Station.
        /// </summary>
        public static string no_station {
            get {
                return ResourceManager.GetString("no_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize Orbital Stations?.
        /// </summary>
        public static string orbital_station_checkbox {
            get {
                return ResourceManager.GetString("orbital_station_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Maximize the allowed search distance to minimize search times..
        /// </summary>
        public static string p1 {
            get {
                return ResourceManager.GetString("p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove_button {
            get {
                return ResourceManager.GetString("remove_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows manual removal of a bookmark..
        /// </summary>
        public static string remove_button_tooltip {
            get {
                return ResourceManager.GetString("remove_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove bookmark.
        /// </summary>
        public static string remove_caption {
            get {
                return ResourceManager.GetString("remove_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the bookmark?.
        /// </summary>
        public static string remove_message {
            get {
                return ResourceManager.GetString("remove_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A successful search triggers a &quot;Route details&quot; event..
        /// </summary>
        public static string route_details_desc {
            get {
                return ResourceManager.GetString("route_details_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute search query.
        /// </summary>
        public static string search_button_tooltip {
            get {
                return ResourceManager.GetString("search_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Search Distance From Main Star (Ls):.
        /// </summary>
        public static string search_distance {
            get {
                return ResourceManager.GetString("search_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Facilities.
        /// </summary>
        public static string search_query_crime_facilitator {
            get {
                return ResourceManager.GetString("search_query_crime_facilitator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoopable Star.
        /// </summary>
        public static string search_query_galaxy_scoop {
            get {
                return ResourceManager.GetString("search_query_galaxy_scoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Missions System.
        /// </summary>
        public static string search_query_missions_expiring {
            get {
                return ResourceManager.GetString("search_query_missions_expiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farthest Mission System.
        /// </summary>
        public static string search_query_missions_farthest {
            get {
                return ResourceManager.GetString("search_query_missions_farthest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Missions System.
        /// </summary>
        public static string search_query_missions_most {
            get {
                return ResourceManager.GetString("search_query_missions_most", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Mission System.
        /// </summary>
        public static string search_query_missions_nearest {
            get {
                return ResourceManager.GetString("search_query_missions_nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest Route System.
        /// </summary>
        public static string search_query_missions_route {
            get {
                return ResourceManager.GetString("search_query_missions_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo Source System.
        /// </summary>
        public static string search_query_missions_source {
            get {
                return ResourceManager.GetString("search_query_missions_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mission System.
        /// </summary>
        public static string search_query_missions_update {
            get {
                return ResourceManager.GetString("search_query_missions_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded Materials Trader.
        /// </summary>
        public static string search_query_services_encoded {
            get {
                return ResourceManager.GetString("search_query_services_encoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Technology Broker.
        /// </summary>
        public static string search_query_services_guardian {
            get {
                return ResourceManager.GetString("search_query_services_guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Technology Broker.
        /// </summary>
        public static string search_query_services_human {
            get {
                return ResourceManager.GetString("search_query_services_human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactured Materials Trader.
        /// </summary>
        public static string search_query_services_manufactured {
            get {
                return ResourceManager.GetString("search_query_services_manufactured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Materials Trader.
        /// </summary>
        public static string search_query_services_raw {
            get {
                return ResourceManager.GetString("search_query_services_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime.
        /// </summary>
        public static string search_type_crime {
            get {
                return ResourceManager.GetString("search_type_crime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galaxy.
        /// </summary>
        public static string search_type_galaxy {
            get {
                return ResourceManager.GetString("search_type_galaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string search_type_missions {
            get {
                return ResourceManager.GetString("search_type_missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string search_type_services {
            get {
                return ResourceManager.GetString("search_type_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string select_button {
            get {
                return ResourceManager.GetString("select_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the selected system &amp; station.
        /// </summary>
        public static string select_button_tooltip {
            get {
                return ResourceManager.GetString("select_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string set_button {
            get {
                return ResourceManager.GetString("set_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the selected bookmark target.
        /// </summary>
        public static string set_button_tooltip {
            get {
                return ResourceManager.GetString("set_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station:.
        /// </summary>
        public static string station_textbox_desc {
            get {
                return ResourceManager.GetString("station_textbox_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System:.
        /// </summary>
        public static string system_textbox_desc {
            get {
                return ResourceManager.GetString("system_textbox_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update_button {
            get {
                return ResourceManager.GetString("update_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the bookmark&apos;s location data from your current in-game position and orientation.
        /// </summary>
        public static string update_button_tooltip {
            get {
                return ResourceManager.GetString("update_button_tooltip", resourceCulture);
            }
        }
    }
}
