//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiSpeechService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiSpeechService.Properties.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to dash.
        /// </summary>
        public static string dash {
            get {
                return ResourceManager.GetString("dash", resourceCulture);
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to minus.
        /// </summary>
        public static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to plus.
        /// </summary>
        public static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point.
        /// </summary>
        public static string point {
            get {
                return ResourceManager.GetString("point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} billion.
        /// </summary>
        public static string shortDecimalBillion {
            get {
                return ResourceManager.GetString("shortDecimalBillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} million.
        /// </summary>
        public static string shortDecimalMillion {
            get {
                return ResourceManager.GetString("shortDecimalMillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} quadrillion.
        /// </summary>
        public static string shortDecimalQuadrillion {
            get {
                return ResourceManager.GetString("shortDecimalQuadrillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} quintillion.
        /// </summary>
        public static string shortDecimalQuintillion {
            get {
                return ResourceManager.GetString("shortDecimalQuintillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thousand.
        /// </summary>
        public static string shortDecimalThousand {
            get {
                return ResourceManager.GetString("shortDecimalThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} trillion.
        /// </summary>
        public static string shortDecimalTrillion {
            get {
                return ResourceManager.GetString("shortDecimalTrillion", resourceCulture);
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to zero.
        /// </summary>
        public static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
    }
}
