<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
        <OutputPath>..\bin\Debug\Application\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
        <OutputPath>..\bin\Release\Application\</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="Properties\pls.xsd" />
        <EmbeddedResource Include="Properties\xml.xsd" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Properties\FormatOverrides.Designer.cs">
            <AutoGen>True</AutoGen>
            <DesignTime>True</DesignTime>
            <DependentUpon>FormatOverrides.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\Phonetics.Designer.cs">
            <AutoGen>True</AutoGen>
            <DesignTime>True</DesignTime>
            <DependentUpon>Phonetics.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\Phrases.Designer.cs">
            <AutoGen>True</AutoGen>
            <DesignTime>True</DesignTime>
            <DependentUpon>Phrases.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\CompanionAppService\EddiCompanionAppService.csproj" />
        <ProjectReference Include="..\ConfigService\EddiConfigService.csproj" />
        <ProjectReference Include="..\DataDefinitions\EddiDataDefinitions.csproj" />
        <ProjectReference Include="..\Utilities\Utilities.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Include="..\Azure Speech Services.md">
            <Link>Azure Speech Services.md</Link>
        </None>
        <None Include="..\Amazon Polly.md">
            <Link>Amazon Polly.md</Link>
        </None>
        <None Include="..\Lexicons.md">
            <Link>Lexicons.md</Link>
        </None>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Properties\FormatOverrides.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>FormatOverrides.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\Phonetics.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Phonetics.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\Phrases.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Phrases.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AWSSDK.Polly" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.CSharp" />
        <PackageReference Include="NAudio" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="NWaves" />
        <PackageReference Include="System.Speech" />
        <PackageReference Include="System.Text.RegularExpressions" />
        <PackageReference Include="Microsoft.CognitiveServices.Speech" />
    </ItemGroup>
    <Target Name="CopyAzureSpeechNativeDlls" AfterTargets="Build">
        <ItemGroup>
            <AzureSpeechNativeFiles Include="$(OutputPath)runtimes\win-x64\native\*.*" />
        </ItemGroup>
        <Copy SourceFiles="@(AzureSpeechNativeFiles)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
    </Target>
</Project>
