<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <UseWPF>true</UseWPF>
        <!--Dynamic loading copies dependencies of dynamically loaded assemblies to the output directory-->
        <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
        <OutputPath>..\bin\Debug\Application\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
        <OutputPath>..\bin\Release\Application\</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\CompanionAppService\EddiCompanionAppService.csproj" />
        <ProjectReference Include="..\DataDefinitions\EddiDataDefinitions.csproj" />
        <ProjectReference Include="..\EddiUI\EddiUI.csproj" />
        <ProjectReference Include="..\EddiInaraService\EddiInaraService.csproj" />
        <ProjectReference Include="..\EddiUI\EddiUI.csproj" />
        <ProjectReference Include="..\EDDI\Eddi.csproj" />
        <ProjectReference Include="..\DataProviderService\EddiDataProviderService.csproj" />
        <ProjectReference Include="..\Events\EddiEvents.csproj" />
        <ProjectReference Include="..\IPC_Service\EddiIPC_Service.csproj" />
        <ProjectReference Include="..\NavigationService\EddiNavigationService.csproj" />
        <ProjectReference Include="..\SpeechResponder\EddiSpeechResponder.csproj" />
        <ProjectReference Include="..\SpeechService\EddiSpeechService.csproj" />
        <ProjectReference Include="..\StarMapService\EddiStarMapService.csproj" />
        <ProjectReference Include="..\Utilities\Utilities.csproj" />
    </ItemGroup>
    <ItemGroup>
        <WCFMetadata Include="Service References\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.CSharp" />
        <PackageReference Include="System.Collections.Immutable" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Properties\VoiceAttack.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>VoiceAttack.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Properties\VoiceAttack.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>VoiceAttack.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <None Update="EDDI.vap">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
