<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
        <OutputPath>..\bin\Debug\Application\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
        <OutputPath>..\bin\Release\Application\</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <Compile Remove="Properties\**" />
        <EmbeddedResource Remove="Properties\**" />
        <None Remove="Properties\**" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\DataDefinitions\EddiDataDefinitions.csproj" />
        <ProjectReference Include="..\ConfigService\EddiConfigService.csproj" />
        <ProjectReference Include="..\Utilities\Utilities.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CSharp" />
    </ItemGroup>
</Project>
