//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiShipMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipMonitor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipMonitor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiShipMonitor.Properties.ShipMonitor", typeof(ShipMonitor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track information on your ships..
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export it.
        /// </summary>
        public static string export_it_button {
            get {
                return ResourceManager.GetString("export_it_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string header_hot {
            get {
                return ResourceManager.GetString("header_hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string header_location {
            get {
                return ResourceManager.GetString("header_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string header_model {
            get {
                return ResourceManager.GetString("header_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string header_name {
            get {
                return ResourceManager.GetString("header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string header_role {
            get {
                return ResourceManager.GetString("header_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship ID.
        /// </summary>
        public static string header_ship_ID {
            get {
                return ResourceManager.GetString("header_ship_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (spoken).
        /// </summary>
        public static string header_spoken_name {
            get {
                return ResourceManager.GetString("header_spoken_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string header_value {
            get {
                return ResourceManager.GetString("header_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hear it.
        /// </summary>
        public static string hear_it_button {
            get {
                return ResourceManager.GetString("hear_it_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/International_Phonetic_Alphabet.
        /// </summary>
        public static string ipa_page {
            get {
                return ResourceManager.GetString("ipa_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online dictionaries may include appropriate IPA pronunciations for common words. The resources below may be used to generate custom pronunciations for less common words..
        /// </summary>
        public static string ipa_page_comments {
            get {
                return ResourceManager.GetString("ipa_page_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string ipa_page_p1 {
            get {
                return ResourceManager.GetString("ipa_page_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is an alphabetic system of phonetic notation based primarily on the Latin alphabet. It was devised by the International Phonetic Association in the late 19th century as a standardized representation of the sounds of spoken language..
        /// </summary>
        public static string ipa_page_p2 {
            get {
                return ResourceManager.GetString("ipa_page_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.internationalphoneticalphabet.org/ipa-sounds/ipa-chart-with-sounds/.
        /// </summary>
        public static string ipa_resource1 {
            get {
                return ResourceManager.GetString("ipa_resource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA chart with sounds.
        /// </summary>
        public static string ipa_resource1_title {
            get {
                return ResourceManager.GetString("ipa_resource1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tophonetics.com/.
        /// </summary>
        public static string ipa_resource2 {
            get {
                return ResourceManager.GetString("ipa_resource2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English to IPA translator - ToPhonetics.com.
        /// </summary>
        public static string ipa_resource2_title {
            get {
                return ResourceManager.GetString("ipa_resource2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://easypronunciation.com/en/english-phonetic-transcription-converter.
        /// </summary>
        public static string ipa_resource3 {
            get {
                return ResourceManager.GetString("ipa_resource3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English to IPA translator - EasyPronunciation.com.
        /// </summary>
        public static string ipa_resource3_title {
            get {
                return ResourceManager.GetString("ipa_resource3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Phonetic Alphabet.
        /// </summary>
        public static string link_ipa {
            get {
                return ResourceManager.GetString("link_ipa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Monitor.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This allows you to see your ships and give them individual roles. The information is made available to responders and is used in scripts to tailor actions..
        /// </summary>
        public static string p1 {
            get {
                return ResourceManager.GetString("p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the name of your ship is hard for EDDI to pronounce then you can add a spoken version of the ship using the.
        /// </summary>
        public static string p2 {
            get {
                return ResourceManager.GetString("p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . For example, if your ship was called &apos;Pride of Achenar&apos; then your spoken name would be &apos;praɪdɒvˈakɜːnɑ&apos; (note no spaces in the phonetic version)..
        /// </summary>
        public static string p3 {
            get {
                return ResourceManager.GetString("p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that if you have not configured access to the Frontier API then some of the data below will be inaccurate or unavailable. Also, if you had multiple ships prior to installing EDDI you will need to swap to them as your primary ship and wait a few moments before full information for them will be available..
        /// </summary>
        public static string p4 {
            get {
                return ResourceManager.GetString("p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDDI can send an export of your ship&apos;s data to Coriolis or EDShipyard (3rd Party tools). Select the tool you prefer..
        /// </summary>
        public static string p5 {
            get {
                return ResourceManager.GetString("p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string ship_clean {
            get {
                return ResourceManager.GetString("ship_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string ship_hot {
            get {
                return ResourceManager.GetString("ship_hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stands ready..
        /// </summary>
        public static string ship_ready {
            get {
                return ResourceManager.GetString("ship_ready", resourceCulture);
            }
        }
    }
}
