# Workflow Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Example: https://github.com/github/VisualStudio/blob/263aac11f57d53c5f9fe64ba9916f77c058974d7/.github/workflows/main.yml
# Build and Test (ref. https://docs.github.com/en/actions/guides/building-and-testing-net)
# Note: Github recommends using full commit SHAs when using 3rd party actions

name: Continuous Integration
concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true
env:
  build-config: Release
  solution: EDDI.sln

  # Build artifact variables
  build-artifact-name: build-artifact

# Define our triggers
on: 
  push:
    branches: 
    - '*'
    - develop
    - '!l10n_develop'
    - '!refs/pull/*'
    paths-ignore:
    - docs/*        # Every file in the root docs folder
    - '**.html'     # HTML files anywhere in the repo
    - '**.md'       # Markdown files anywhere in the repo
    - '**.resx'     # RESX files anywhere in the repo
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
    - develop
    paths-ignore:
    - docs/*        # Every file in the root docs folder
    - '**.html'     # HTML files anywhere in the repo
    - '**.md'       # Markdown files anywhere in the repo
    - '**.resx'     # RESX files anywhere in the repo
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │  * indicates 'all'
    #        │  │ │ │ │  Ref. https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 2 * * 0' # Runs at 2:30 AM UTC, any day of the month, any month of the year, on Sundays

jobs:
  build:
    name: Build & Test
    runs-on: windows-latest
    steps:
    - name: Check out the repository on the workflow runner
      uses: actions/checkout@v7

    # Build
    - name: Add msbuild.exe to PATH
      uses: microsoft/setup-msbuild@v3
    - name: Add nuget to PATH
      uses: nuget/setup-nuget@v4.0
      with:
        nuget-version: 'latest'
    - name: Restore dependencies
      run: nuget restore ${{ env.solution }} -NonInteractive
    - name: Build our solution
      id: build
      run: msbuild ${{ env.solution }} /p:Configuration=${{ env.build-config }} /p:Platform=x64 /p:UseSharedCompilation=false /verbosity:minimal
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.build-artifact-name }}
        path: ./bin/Release/*
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    # Perform unit testing
    - name: Test our solution
      run: dotnet test Tests\Tests.csproj -c ${{ env.build-config }} --no-build --no-restore --filter "TestCategory=UnitTests" -p:SolutionDir="${{ github.workspace }}\" -p:Platform=x64 --results-directory "${{ github.workspace }}\TestResults\${{ env.build-config }}" --logger:"console;verbosity=detailed" --logger:"trx;LogFileName=${{ env.build-config }}-ci-tests.trx" --blame-hang --blame-hang-timeout 5m --blame-hang-dump-type mini
