# Workflow Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Example: https://github.com/github/VisualStudio/blob/263aac11f57d53c5f9fe64ba9916f77c058974d7/.github/workflows/main.yml

name: Continuous Integration
env:
  config: Release
  solution: EDDI.sln

# Define our triggers
# Since we are configuring the triggers, we need to specify each set of triggering conditions separately
on:
  push:
    paths-ignore:
    - docs/*        # Every file in the root docs folder
    - '**.html'     # HTML files anywhere in the repo
    - '**.md'       # Markdown files anywhere in the repo
    - '**.resx'     # RESX files anywhere in the repo
  pull_request:
    paths-ignore:
    - docs/*        # Every file in the root docs folder
    - '**.html'     # HTML files anywhere in the repo
    - '**.md'       # Markdown files anywhere in the repo
    - '**.resx'     # RESX files anywhere in the repo

# Build and Test (ref. https://docs.github.com/en/actions/guides/building-and-testing-net)
jobs:
  build:
    runs-on: windows-latest
    steps:
    # Checkout
    - name: Check out the repository on the workflow runner
      uses: actions/checkout@v2.3.4
    # Setup our PATH
    - name: Add msbuild.exe to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Add VSTest.console.exe to PATH
      uses: darenm/Setup-VSTest@v1.1.1
    - uses: nuget/setup-nuget@v1.0.5
      with:
        nuget-version: 'latest'
    # Setup our dependencies
    - name: Retrieve any cached copies of dependencies (these may be stored for up to a week)
      uses: actions/cache@main
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore or install any missing any dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: nuget restore ${{ env.solution }}
    # Build
    - name: Build our solution (using the environment variables configured above)
      run: msbuild ${{ env.solution }} /p:Configuration=${{ env.config }} /verbosity:minimal
    # Test
    - name: Make a TestResults directory (if it does not already exist)
      run: mkdir -p ./TestResults
    - name: Test our solution and generate a coverage report using OpenCover
      run: ~/.nuget/packages/OpenCover/4.6.519/tools/OpenCover.Console.exe -mergebyhash -skipautoprops -excludebyattribute:*.ExcludeFromCodeCoverage*,*.GeneratedCodeAttribute* -excludebyfile:*\*.Designer.cs,*.xaml -filter:"+[Eddi*]* +[Utilities*]* +[Tests*]UnitTests*" -register:Path32 -target:vstest.console.exe -targetargs:"Tests/bin/Release/Tests.dll /tests:UnitTests /Parallel /InIsolation /Blame" -output:"./TestResults/coverage.xml"
    # Upload coverage results
    - name: Upload coverage to CodeCov (ref. https://github.com/codecov/codecov-action)
      uses: codecov/codecov-action@master
      with:
        files: TestResults/coverage.xml
