//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CombatRatings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CombatRatings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.CombatRatings", typeof(CombatRatings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competent.
        /// </summary>
        public static string Competent {
            get {
                return ResourceManager.GetString("Competent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous.
        /// </summary>
        public static string Dangerous {
            get {
                return ResourceManager.GetString("Dangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadly.
        /// </summary>
        public static string Deadly {
            get {
                return ResourceManager.GetString("Deadly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite.
        /// </summary>
        public static string Elite {
            get {
                return ResourceManager.GetString("Elite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmless.
        /// </summary>
        public static string Harmless {
            get {
                return ResourceManager.GetString("Harmless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly Harmless.
        /// </summary>
        public static string MostlyHarmless {
            get {
                return ResourceManager.GetString("MostlyHarmless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice.
        /// </summary>
        public static string Novice {
            get {
                return ResourceManager.GetString("Novice", resourceCulture);
            }
        }
    }
}
