//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeologyClassDesc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeologyClassDesc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.GeologyClassDesc", typeof(GeologyClassDesc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Type anomolies are a range of phenomena characterised by slow-moving elements..
        /// </summary>
        public static string E_TypeAnomoly {
            get {
                return ResourceManager.GetString("E_TypeAnomoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fumaroles are gaps in a planet’s crust through which gases and steam are emitted. The ejected material often accumulates around the opening..
        /// </summary>
        public static string Fumarole {
            get {
                return ResourceManager.GetString("Fumarole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas vents are the result of internal pressure high enough to burst through a planet’s crust..
        /// </summary>
        public static string GasVent {
            get {
                return ResourceManager.GetString("GasVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice fumaroles are gaps in an icy planet’s crust that allow liquid or gaseous material to escape under high pressure..
        /// </summary>
        public static string IceFumarole {
            get {
                return ResourceManager.GetString("IceFumarole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice geysers, also known as cryogeysers, are eruptions of ice, dust and volatiles..
        /// </summary>
        public static string IceGeyser {
            get {
                return ResourceManager.GetString("IceGeyser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-Type anomolies are a range of high-energy phenomena characterised by luminous cloud patterns..
        /// </summary>
        public static string K_TypeAnomoly {
            get {
                return ResourceManager.GetString("K_TypeAnomoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L-Type anomolies are a range of phenomena characterised by luminous clusters of energy..
        /// </summary>
        public static string L_TypeAnomoly {
            get {
                return ResourceManager.GetString("L_TypeAnomoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagrange clouds are a dense accumulation of gas fixed in place at a Lagrange point, where the combined gravitational forces of multiple bodies create a stable region..
        /// </summary>
        public static string LagrangeCloud {
            get {
                return ResourceManager.GetString("LagrangeCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lava spouts are weakened areas of a planet’s surface where molten material percolates, generating heat and emitting vapour and gases. The nature of the material varies according to the planet’s composition and circumstances..
        /// </summary>
        public static string LavaSpout {
            get {
                return ResourceManager.GetString("LavaSpout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-Type anomolies are a range of phenomena characterised by intensily bright energy patterns..
        /// </summary>
        public static string P_TypeAnomoly {
            get {
                return ResourceManager.GetString("P_TypeAnomoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-Type anomolies are a range of phenomena characterised by energetic center orbs..
        /// </summary>
        public static string Q_TypeAnomoly {
            get {
                return ResourceManager.GetString("Q_TypeAnomoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm clouds are a dense accumulation of gas fixed in place at a Lagrange point, where the combined gravitational forces of multiple bodies create a stable region..
        /// </summary>
        public static string StormCloud {
            get {
                return ResourceManager.GetString("StormCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Type anomolies are a range of phenomena characterised by the presence of a bright pulsing sphere..
        /// </summary>
        public static string T_TypeAnomoly {
            get {
                return ResourceManager.GetString("T_TypeAnomoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geysers are eruptions of liquid created by pressure from local geological activity..
        /// </summary>
        public static string WaterGeyser {
            get {
                return ResourceManager.GetString("WaterGeyser", resourceCulture);
            }
        }
    }
}
