//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Governments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Governments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.Governments", typeof(Governments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anarchy.
        /// </summary>
        public static string Anarchy {
            get {
                return ResourceManager.GetString("Anarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colony.
        /// </summary>
        public static string Colony {
            get {
                return ResourceManager.GetString("Colony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communism.
        /// </summary>
        public static string Communism {
            get {
                return ResourceManager.GetString("Communism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confederacy.
        /// </summary>
        public static string Confederacy {
            get {
                return ResourceManager.GetString("Confederacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperative.
        /// </summary>
        public static string Cooperative {
            get {
                return ResourceManager.GetString("Cooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string Corporate {
            get {
                return ResourceManager.GetString("Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Democracy.
        /// </summary>
        public static string Democracy {
            get {
                return ResourceManager.GetString("Democracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictatorship.
        /// </summary>
        public static string Dictatorship {
            get {
                return ResourceManager.GetString("Dictatorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string engineer {
            get {
                return ResourceManager.GetString("engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feudal.
        /// </summary>
        public static string Feudal {
            get {
                return ResourceManager.GetString("Feudal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        public static string Imperial {
            get {
                return ResourceManager.GetString("Imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronage.
        /// </summary>
        public static string Patronage {
            get {
                return ResourceManager.GetString("Patronage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Colony.
        /// </summary>
        public static string PrisonColony {
            get {
                return ResourceManager.GetString("PrisonColony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theocracy.
        /// </summary>
        public static string Theocracy {
            get {
                return ResourceManager.GetString("Theocracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
    }
}
