//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HandWeaponMod {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HandWeaponMod() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.HandWeaponMod", typeof(HandWeaponMod).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip Fire Accuracy.
        /// </summary>
        public static string weapon_accuracy {
            get {
                return ResourceManager.GetString("weapon_accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stowed Reloading.
        /// </summary>
        public static string weapon_backpackreloading {
            get {
                return ResourceManager.GetString("weapon_backpackreloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine Size.
        /// </summary>
        public static string weapon_clipsize {
            get {
                return ResourceManager.GetString("weapon_clipsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster Handling.
        /// </summary>
        public static string weapon_handling {
            get {
                return ResourceManager.GetString("weapon_handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshot Damage.
        /// </summary>
        public static string weapon_headshotdamage {
            get {
                return ResourceManager.GetString("weapon_headshotdamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Range.
        /// </summary>
        public static string weapon_range {
            get {
                return ResourceManager.GetString("weapon_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Speed.
        /// </summary>
        public static string weapon_reloadspeed {
            get {
                return ResourceManager.GetString("weapon_reloadspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string weapon_scope {
            get {
                return ResourceManager.GetString("weapon_scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability.
        /// </summary>
        public static string weapon_stability {
            get {
                return ResourceManager.GetString("weapon_stability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Suppressor.
        /// </summary>
        public static string weapon_suppression_pressurised {
            get {
                return ResourceManager.GetString("weapon_suppression_pressurised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Masking.
        /// </summary>
        public static string weapon_suppression_unpressurised {
            get {
                return ResourceManager.GetString("weapon_suppression_unpressurised", resourceCulture);
            }
        }
    }
}
