//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaterialLocations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaterialLocations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.MaterialLocations", typeof(MaterialLocations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning satellites orbiting installations and populated Earth-like worlds, or as a mission reward... especially for planetary scan missions..
        /// </summary>
        public static string adaptiveencryptors {
            get {
                return ResourceManager.GetString("adaptiveencryptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string ancientbiologicaldata {
            get {
                return ResourceManager.GetString("ancientbiologicaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string ancientculturaldata {
            get {
                return ResourceManager.GetString("ancientculturaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string ancienthistoricaldata {
            get {
                return ResourceManager.GetString("ancienthistoricaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string ancientlanguagedata {
            get {
                return ResourceManager.GetString("ancientlanguagedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string ancienttechnologicaldata {
            get {
                return ResourceManager.GetString("ancienttechnologicaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting..
        /// </summary>
        public static string antimony {
            get {
                return ResourceManager.GetString("antimony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from signal sources or as a mission reward, especially in systems with booming economies..
        /// </summary>
        public static string archivedemissiondata {
            get {
                return ResourceManager.GetString("archivedemissiondata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting, asteroid mining, or as a mission reward..
        /// </summary>
        public static string arsenic {
            get {
                return ResourceManager.GetString("arsenic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels..
        /// </summary>
        public static string basicconductors {
            get {
                return ResourceManager.GetString("basicconductors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained as a mission reward..
        /// </summary>
        public static string biotechconductors {
            get {
                return ResourceManager.GetString("biotechconductors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by asteroid mining..
        /// </summary>
        public static string boron {
            get {
                return ResourceManager.GetString("boron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning haulage vessels or as a mission reward..
        /// </summary>
        public static string bulkscandata {
            get {
                return ResourceManager.GetString("bulkscandata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or asteroid mining..
        /// </summary>
        public static string cadmium {
            get {
                return ResourceManager.GetString("cadmium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting, asteroid mining, and ice ring mining..
        /// </summary>
        public static string carbon {
            get {
                return ResourceManager.GetString("carbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels..
        /// </summary>
        public static string chemicaldistillery {
            get {
                return ResourceManager.GetString("chemicaldistillery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of large haulage vessels, commonly Type-7s and Type 9s, especially in systems in anarchy or suffering from disease.  These are also available at Dav&apos;s Hope.&quot;.
        /// </summary>
        public static string chemicalmanipulators {
            get {
                return ResourceManager.GetString("chemicalmanipulators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels or as a mission reward..
        /// </summary>
        public static string chemicalprocessors {
            get {
                return ResourceManager.GetString("chemicalprocessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels..
        /// </summary>
        public static string chemicalstorageunits {
            get {
                return ResourceManager.GetString("chemicalstorageunits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting, asteroid mining in pristine rocky rings, or by mining ice rings..
        /// </summary>
        public static string chromium {
            get {
                return ResourceManager.GetString("chromium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning datalinks in ground bases, by scanning military and authority ships, or as a mission reward, espcially in systems with booming economies..
        /// </summary>
        public static string classifiedscandata {
            get {
                return ResourceManager.GetString("classifiedscandata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from degraded signal sources, including surface signals..
        /// </summary>
        public static string compactcomposites {
            get {
                return ResourceManager.GetString("compactcomposites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning combat vessels, scanning deep space data beacons and encoded emissions sources, or as a mission reward..
        /// </summary>
        public static string compactemissionsdata {
            get {
                return ResourceManager.GetString("compactemissionsdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels or as a mission reward and encoded emissions sources, especially in high security systems, systems with booming economies, and systems seeking to retreat and consolidate power.  These are also available at Dav&apos;s Hope..
        /// </summary>
        public static string compoundshielding {
            get {
                return ResourceManager.GetString("compoundshielding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels, especially in anarchy systems near population systems.  These are also available at Dav&apos;s Hope..
        /// </summary>
        public static string conductiveceramics {
            get {
                return ResourceManager.GetString("conductiveceramics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels, especially in anarchy systems near population systems. .
        /// </summary>
        public static string conductivecomponents {
            get {
                return ResourceManager.GetString("conductivecomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of large haulage and passenger vessels such as Type-9s and Beluga liners, from surface signal sources, and as a mission reward.  These are also available at Dav&apos;s Hope..
        /// </summary>
        public static string conductivepolymers {
            get {
                return ResourceManager.GetString("conductivepolymers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels, especially in low security systems. These are also available at Dav&apos;s Hope..
        /// </summary>
        public static string configurablecomponents {
            get {
                return ResourceManager.GetString("configurablecomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained as a mission reward or by scanning datalinks in ground bases or scanning private data beacons in encoded signal sources while systems are in elections or civil wars..
        /// </summary>
        public static string consumerfirmware {
            get {
                return ResourceManager.GetString("consumerfirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat ships, and from surface signal sources..
        /// </summary>
        public static string crystalshards {
            get {
                return ResourceManager.GetString("crystalshards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning frame shift high wakes of vessels, scanning encoded data beacons, or as a mission reward..
        /// </summary>
        public static string dataminedwake {
            get {
                return ResourceManager.GetString("dataminedwake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning system authority vessels or as a mission reward..
        /// </summary>
        public static string decodedemissiondata {
            get {
                return ResourceManager.GetString("decodedemissiondata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning frame shift high wakes of vessels or as a mission reward, especially in systems with booming economies..
        /// </summary>
        public static string disruptedwakeechoes {
            get {
                return ResourceManager.GetString("disruptedwakeechoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat and system authority vessels, or from degraded emissions sources in anarchy systems near other populated systems..
        /// </summary>
        public static string electrochemicalarrays {
            get {
                return ResourceManager.GetString("electrochemicalarrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning datalinks in ground bases or as a mission reward..
        /// </summary>
        public static string embeddedfirmware {
            get {
                return ResourceManager.GetString("embeddedfirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from scanning combat vessels or in signal sources, especially in systems with booming economies or undergoing an election..
        /// </summary>
        public static string emissiondata {
            get {
                return ResourceManager.GetString("emissiondata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning datalinks in ground bases or as a mission reward..
        /// </summary>
        public static string encodedscandata {
            get {
                return ResourceManager.GetString("encodedscandata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from signal sources, including surface signal sources, or as a mission reward. These tend to be more common in systems with booming economies..
        /// </summary>
        public static string encryptedfiles {
            get {
                return ResourceManager.GetString("encryptedfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning datalinks in ground bases..
        /// </summary>
        public static string encryptionarchives {
            get {
                return ResourceManager.GetString("encryptionarchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning surface data points, satellites orbiting installations and populated Earth-like worlds, or as a mission reward, especially in systems with booming economies..
        /// </summary>
        public static string encryptioncodes {
            get {
                return ResourceManager.GetString("encryptioncodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels or as a mission reward, especially in systems with booming economies..
        /// </summary>
        public static string exquisitefocuscrystals {
            get {
                return ResourceManager.GetString("exquisitefocuscrystals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources in systems under Federal control or from the wreckage of Federal combat vessels..
        /// </summary>
        public static string fedcorecomposites {
            get {
                return ResourceManager.GetString("fedcorecomposites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources Federal control or as a mission reward in Federal systems during elections..
        /// </summary>
        public static string fedproprietarycomposites {
            get {
                return ResourceManager.GetString("fedproprietarycomposites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of military and authority ships..
        /// </summary>
        public static string filamentcomposites {
            get {
                return ResourceManager.GetString("filamentcomposites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels, especially in high security systems..
        /// </summary>
        public static string focuscrystals {
            get {
                return ResourceManager.GetString("focuscrystals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning frame shift high wakes of vessels or as a mission reward..
        /// </summary>
        public static string fsdtelemetry {
            get {
                return ResourceManager.GetString("fsdtelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels or as a mission reward, especially in systems holding elections..
        /// </summary>
        public static string galvanisingalloys {
            get {
                return ResourceManager.GetString("galvanisingalloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or as a mission reward, especially in systems suffering from disease..
        /// </summary>
        public static string germanium {
            get {
                return ResourceManager.GetString("germanium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of small combat vessels or as a mission reward..
        /// </summary>
        public static string gridresistors {
            get {
                return ResourceManager.GetString("gridresistors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string guardian_moduleblueprint {
            get {
                return ResourceManager.GetString("guardian_moduleblueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string guardian_powercell {
            get {
                return ResourceManager.GetString("guardian_powercell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string guardian_powerconduit {
            get {
                return ResourceManager.GetString("guardian_powerconduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string guardian_sentinel_weaponparts {
            get {
                return ResourceManager.GetString("guardian_sentinel_weaponparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string guardian_sentinel_wreckagecomponents {
            get {
                return ResourceManager.GetString("guardian_sentinel_wreckagecomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string guardian_techcomponent {
            get {
                return ResourceManager.GetString("guardian_techcomponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string guardian_vesselblueprint {
            get {
                return ResourceManager.GetString("guardian_vesselblueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the ancient ruins of the alien species known as the Guardians..
        /// </summary>
        public static string guardian_weaponblueprint {
            get {
                return ResourceManager.GetString("guardian_weaponblueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels, in signal sources or as a mission reward..
        /// </summary>
        public static string heatconductionwiring {
            get {
                return ResourceManager.GetString("heatconductionwiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels in signal sources, especially in systems with boming economies, or as a mission reward..
        /// </summary>
        public static string heatdispersionplate {
            get {
                return ResourceManager.GetString("heatdispersionplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels, especially in anarchy systems near other popualted systems..
        /// </summary>
        public static string heatexchangers {
            get {
                return ResourceManager.GetString("heatexchangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of military and authority ships..
        /// </summary>
        public static string heatresistantceramics {
            get {
                return ResourceManager.GetString("heatresistantceramics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels or as a mission reward.  These are also available at Dav&apos;s Hope..
        /// </summary>
        public static string heatvanes {
            get {
                return ResourceManager.GetString("heatvanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of large combat vessels, commonly Anacondas and Federal Corvettes.  These are also available at Dav&apos;s Hope..
        /// </summary>
        public static string highdensitycomposites {
            get {
                return ResourceManager.GetString("highdensitycomposites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of large combat vessels, commonly Anacondas and Federal Corvettes, or as a mission reward..
        /// </summary>
        public static string hybridcapacitors {
            get {
                return ResourceManager.GetString("hybridcapacitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning frame shift high wakes of vessels..
        /// </summary>
        public static string hyperspacetrajectories {
            get {
                return ResourceManager.GetString("hyperspacetrajectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources in systems under Imperial control or as a mission reward..
        /// </summary>
        public static string imperialshielding {
            get {
                return ResourceManager.GetString("imperialshielding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources in systems in independent space, systems with booming economies, systems suffering from civil unrest, war, civil war, or disease, or as a mission reward..
        /// </summary>
        public static string improvisedcomponents {
            get {
                return ResourceManager.GetString("improvisedcomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning datalinks in ground bases or as a mission reward..
        /// </summary>
        public static string industrialfirmware {
            get {
                return ResourceManager.GetString("industrialfirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting, asteroid mining, or ice ring mining..
        /// </summary>
        public static string iron {
            get {
                return ResourceManager.GetString("iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from asteroid mining..
        /// </summary>
        public static string lead {
            get {
                return ResourceManager.GetString("lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning surface data points, satellites orbiting installations and populated Earth-like worlds, or as a mission reward..
        /// </summary>
        public static string legacyfirmware {
            get {
                return ResourceManager.GetString("legacyfirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or as a mission reward..
        /// </summary>
        public static string manganese {
            get {
                return ResourceManager.GetString("manganese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of small haulage vessels, especially in low security systems.  These are also available at Dav&apos;s Hope..
        /// </summary>
        public static string mechanicalcomponents {
            get {
                return ResourceManager.GetString("mechanicalcomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels, especially in systems with booming economies..
        /// </summary>
        public static string mechanicalequipment {
            get {
                return ResourceManager.GetString("mechanicalequipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of haulage vessels or as mission reward..
        /// </summary>
        public static string mechanicalscrap {
            get {
                return ResourceManager.GetString("mechanicalscrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting..
        /// </summary>
        public static string mercury {
            get {
                return ResourceManager.GetString("mercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources in war or civil war systems or as a mission reward..
        /// </summary>
        public static string militarygradealloys {
            get {
                return ResourceManager.GetString("militarygradealloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources in war or civil war systems or as a mission reward..
        /// </summary>
        public static string militarysupercapacitors {
            get {
                return ResourceManager.GetString("militarysupercapacitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or asteroid mining..
        /// </summary>
        public static string molybdenum {
            get {
                return ResourceManager.GetString("molybdenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting, asteroid mining, or ice ring mining..
        /// </summary>
        public static string nickel {
            get {
                return ResourceManager.GetString("nickel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or asteroid mining..
        /// </summary>
        public static string niobium {
            get {
                return ResourceManager.GetString("niobium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources, especially in outbreak systems, or as a mission reward..
        /// </summary>
        public static string pharmaceuticalisolators {
            get {
                return ResourceManager.GetString("pharmaceuticalisolators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels or in signal sources in systems with booming economies..
        /// </summary>
        public static string phasealloys {
            get {
                return ResourceManager.GetString("phasealloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting, asteroid mining, or ice mining..
        /// </summary>
        public static string phosphorus {
            get {
                return ResourceManager.GetString("phosphorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or as a mission reward..
        /// </summary>
        public static string polonium {
            get {
                return ResourceManager.GetString("polonium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained  from the wreckage of combat and system authority vessels, signal sources with convoy dispersal patterns or as a mission reward..
        /// </summary>
        public static string polymercapacitors {
            get {
                return ResourceManager.GetString("polymercapacitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat and system authority vessels or as mission reward..
        /// </summary>
        public static string precipitatedalloys {
            get {
                return ResourceManager.GetString("precipitatedalloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources in systems with booming economies or as a mission reward..
        /// </summary>
        public static string protoheatradiators {
            get {
                return ResourceManager.GetString("protoheatradiators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources in systems with booming economies or as a mission reward..
        /// </summary>
        public static string protolightalloys {
            get {
                return ResourceManager.GetString("protolightalloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in high-grade signal sources in systems with booming economies..
        /// </summary>
        public static string protoradiolicalloys {
            get {
                return ResourceManager.GetString("protoradiolicalloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained in active combat signal sources or as mission reward..
        /// </summary>
        public static string refinedfocuscrystals {
            get {
                return ResourceManager.GetString("refinedfocuscrystals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from asteroid mining..
        /// </summary>
        public static string rhenium {
            get {
                return ResourceManager.GetString("rhenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting..
        /// </summary>
        public static string ruthenium {
            get {
                return ResourceManager.GetString("ruthenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels..
        /// </summary>
        public static string salvagedalloys {
            get {
                return ResourceManager.GetString("salvagedalloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from scanning haulage vessels, especially in systems with booming economies..
        /// </summary>
        public static string scanarchives {
            get {
                return ResourceManager.GetString("scanarchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning large haulage vessels, commonly Type-7s and Type-9s, and by scanning datalinks in ground bases..
        /// </summary>
        public static string scandatabanks {
            get {
                return ResourceManager.GetString("scandatabanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from scanning vessels, signal sources, or as a mission reward..
        /// </summary>
        public static string scrambledemissiondata {
            get {
                return ResourceManager.GetString("scrambledemissiondata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning datalinks in ground bases or as a mission reward..
        /// </summary>
        public static string securityfirmware {
            get {
                return ResourceManager.GetString("securityfirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or as a mission reward..
        /// </summary>
        public static string selenium {
            get {
                return ResourceManager.GetString("selenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning haulage vessels or as a mission reward..
        /// </summary>
        public static string shieldcyclerecordings {
            get {
                return ResourceManager.GetString("shieldcyclerecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning combat vessels..
        /// </summary>
        public static string shielddensityreports {
            get {
                return ResourceManager.GetString("shielddensityreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels or in signal sources, especially in systems with booming economies..
        /// </summary>
        public static string shieldemitters {
            get {
                return ResourceManager.GetString("shieldemitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from scanning vessels or as a mission reward..
        /// </summary>
        public static string shieldfrequencydata {
            get {
                return ResourceManager.GetString("shieldfrequencydata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels or as a mission reward..
        /// </summary>
        public static string shieldingsensors {
            get {
                return ResourceManager.GetString("shieldingsensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning system authority and combat vessels, or as a mission reward, especially in systems with booming economies..
        /// </summary>
        public static string shieldpatternanalysis {
            get {
                return ResourceManager.GetString("shieldpatternanalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning haulage vessels or as a mission reward, especially in system swith booming economies..
        /// </summary>
        public static string shieldsoakanalysis {
            get {
                return ResourceManager.GetString("shieldsoakanalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting, asteroid mining, or ice ring mining..
        /// </summary>
        public static string sulphur {
            get {
                return ResourceManager.GetString("sulphur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning datalinks in ground bases, or in signal sources or as a mission reward..
        /// </summary>
        public static string symmetrickeys {
            get {
                return ResourceManager.GetString("symmetrickeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting..
        /// </summary>
        public static string technetium {
            get {
                return ResourceManager.GetString("technetium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting..
        /// </summary>
        public static string tellurium {
            get {
                return ResourceManager.GetString("tellurium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat ships..
        /// </summary>
        public static string temperedalloys {
            get {
                return ResourceManager.GetString("temperedalloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of Thargoid vessels..
        /// </summary>
        public static string tg_biomechanicalconduits {
            get {
                return ResourceManager.GetString("tg_biomechanicalconduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids..
        /// </summary>
        public static string tg_compositiondata {
            get {
                return ResourceManager.GetString("tg_compositiondata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of Thargoid vessels..
        /// </summary>
        public static string tg_propulsionelement {
            get {
                return ResourceManager.GetString("tg_propulsionelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids..
        /// </summary>
        public static string tg_residuedata {
            get {
                return ResourceManager.GetString("tg_residuedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from scanning Thargoid vessels..
        /// </summary>
        public static string tg_shipflightdata {
            get {
                return ResourceManager.GetString("tg_shipflightdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from scanning Thargoid vessels..
        /// </summary>
        public static string tg_shipsystemsdata {
            get {
                return ResourceManager.GetString("tg_shipsystemsdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids..
        /// </summary>
        public static string tg_structuraldata {
            get {
                return ResourceManager.GetString("tg_structuraldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of Thargoid vessels..
        /// </summary>
        public static string tg_weaponparts {
            get {
                return ResourceManager.GetString("tg_weaponparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of Thargoid vessels..
        /// </summary>
        public static string tg_wreckagecomponents {
            get {
                return ResourceManager.GetString("tg_wreckagecomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels or as a mission reward..
        /// </summary>
        public static string thermicalloys {
            get {
                return ResourceManager.GetString("thermicalloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or asteroid mining in areas with pristine reserves..
        /// </summary>
        public static string tin {
            get {
                return ResourceManager.GetString("tin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting..
        /// </summary>
        public static string tungsten {
            get {
                return ResourceManager.GetString("tungsten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels or in combat aftermath signal sources..
        /// </summary>
        public static string uncutfocuscrystals {
            get {
                return ResourceManager.GetString("uncutfocuscrystals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids..
        /// </summary>
        public static string unknowncarapace {
            get {
                return ResourceManager.GetString("unknowncarapace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids..
        /// </summary>
        public static string unknownenergycell {
            get {
                return ResourceManager.GetString("unknownenergycell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids..
        /// </summary>
        public static string unknownenergysource {
            get {
                return ResourceManager.GetString("unknownenergysource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids..
        /// </summary>
        public static string unknownorganiccircuitry {
            get {
                return ResourceManager.GetString("unknownorganiccircuitry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids or scanning a Thargoid vessel..
        /// </summary>
        public static string unknownshipsignature {
            get {
                return ResourceManager.GetString("unknownshipsignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the mysterious surface sites of the alien species known as the Thargoids..
        /// </summary>
        public static string unknowntechnologycomponents {
            get {
                return ResourceManager.GetString("unknowntechnologycomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning the wake left behind by a Thargoid vessel..
        /// </summary>
        public static string unknownwakedata {
            get {
                return ResourceManager.GetString("unknownwakedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting, mining pristine metallic rings, or mining icy rings..
        /// </summary>
        public static string vanadium {
            get {
                return ResourceManager.GetString("vanadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by scanning frame shift high wakes of vessels or as a mission reward, especially in systems with booming economies..
        /// </summary>
        public static string wakesolutions {
            get {
                return ResourceManager.GetString("wakesolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from the wreckage of combat vessels..
        /// </summary>
        public static string wornshieldemitters {
            get {
                return ResourceManager.GetString("wornshieldemitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting..
        /// </summary>
        public static string yttrium {
            get {
                return ResourceManager.GetString("yttrium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting..
        /// </summary>
        public static string zinc {
            get {
                return ResourceManager.GetString("zinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained from surface prospecting or asteroid mining..
        /// </summary>
        public static string zirconium {
            get {
                return ResourceManager.GetString("zirconium", resourceCulture);
            }
        }
    }
}
