//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Modifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.Modifications", typeof(Modifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightweight Armour .
        /// </summary>
        internal static string ArmourAdvanced {
            get {
                return ResourceManager.GetString("ArmourAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast Resistant Armour.
        /// </summary>
        internal static string ArmourExplosive {
            get {
                return ResourceManager.GetString("ArmourExplosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Duty Armour.
        /// </summary>
        internal static string ArmourHeavyDuty {
            get {
                return ResourceManager.GetString("ArmourHeavyDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinetic Resistant Armour.
        /// </summary>
        internal static string ArmourKinetic {
            get {
                return ResourceManager.GetString("ArmourKinetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Resistant Armour.
        /// </summary>
        internal static string ArmourThermic {
            get {
                return ResourceManager.GetString("ArmourThermic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirty Drive Tuning.
        /// </summary>
        internal static string EngineDirty {
            get {
                return ResourceManager.GetString("EngineDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Strengthening.
        /// </summary>
        internal static string EngineReinforced {
            get {
                return ResourceManager.GetString("EngineReinforced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Drive Tuning.
        /// </summary>
        internal static string EngineTuned {
            get {
                return ResourceManager.GetString("EngineTuned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster FSD Boot Sequence.
        /// </summary>
        internal static string FSDFastBoot {
            get {
                return ResourceManager.GetString("FSDFastBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded FSD Interdictor Capture Arc.
        /// </summary>
        internal static string FSDinterdictorExpanded {
            get {
                return ResourceManager.GetString("FSDinterdictorExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longer Range FSD Interdictor.
        /// </summary>
        internal static string FSDinterdictorLongRange {
            get {
                return ResourceManager.GetString("FSDinterdictorLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased FSD Range.
        /// </summary>
        internal static string FSDLongRange {
            get {
                return ResourceManager.GetString("FSDLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shielded FSD.
        /// </summary>
        internal static string FSDShielded {
            get {
                return ResourceManager.GetString("FSDShielded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightweight Hull Reinforcement.
        /// </summary>
        internal static string HullReinforcementAdvanced {
            get {
                return ResourceManager.GetString("HullReinforcementAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast Resistant Hull Reinforcement.
        /// </summary>
        internal static string HullReinforcementExplosive {
            get {
                return ResourceManager.GetString("HullReinforcementExplosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Duty Hull Reinforcement.
        /// </summary>
        internal static string HullReinforcementHeavyDuty {
            get {
                return ResourceManager.GetString("HullReinforcementHeavyDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinetic Resistant Hull Reinforcement.
        /// </summary>
        internal static string HullReinforcementKinetic {
            get {
                return ResourceManager.GetString("HullReinforcementKinetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Resistant Hull Reinforcement.
        /// </summary>
        internal static string HullReinforcementThermic {
            get {
                return ResourceManager.GetString("HullReinforcementThermic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaff Ammo Capacity.
        /// </summary>
        internal static string MiscChaffCapacity {
            get {
                return ResourceManager.GetString("MiscChaffCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatsink Ammo Capacity.
        /// </summary>
        internal static string MiscHeatSinkCapacity {
            get {
                return ResourceManager.GetString("MiscHeatSinkCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Lightweight.
        /// </summary>
        internal static string MiscLightWeight {
            get {
                return ResourceManager.GetString("MiscLightWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Defence Ammo Capacity.
        /// </summary>
        internal static string MiscPointDefenseCapacity {
            get {
                return ResourceManager.GetString("MiscPointDefenseCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Reinforced .
        /// </summary>
        internal static string MiscReinforced {
            get {
                return ResourceManager.GetString("MiscReinforced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Shielded.
        /// </summary>
        internal static string MiscShielded {
            get {
                return ResourceManager.GetString("MiscShielded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Charge Capacity Power Distributor.
        /// </summary>
        internal static string PowerDistributorHighCapacity {
            get {
                return ResourceManager.GetString("PowerDistributorHighCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Enhanced Power Distributor.
        /// </summary>
        internal static string PowerDistributorHighFrequency {
            get {
                return ResourceManager.GetString("PowerDistributorHighFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Focused Power Distributor.
        /// </summary>
        internal static string PowerDistributorPriorityEngine {
            get {
                return ResourceManager.GetString("PowerDistributorPriorityEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Focused Power Distributor.
        /// </summary>
        internal static string PowerDistributorPrioritySystem {
            get {
                return ResourceManager.GetString("PowerDistributorPrioritySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Focused Power Distributor.
        /// </summary>
        internal static string PowerDistributorPriorityWeapon {
            get {
                return ResourceManager.GetString("PowerDistributorPriorityWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shielded Power Distributor.
        /// </summary>
        internal static string PowerDistributorShielded {
            get {
                return ResourceManager.GetString("PowerDistributorShielded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoured Power Plant.
        /// </summary>
        internal static string PowerPlantArmoured {
            get {
                return ResourceManager.GetString("PowerPlantArmoured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcharged Power Plant.
        /// </summary>
        internal static string PowerPlantBoosted {
            get {
                return ResourceManager.GetString("PowerPlantBoosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Emissions Power Plant.
        /// </summary>
        internal static string PowerPlantStealth {
            get {
                return ResourceManager.GetString("PowerPlantStealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded Probe Scanning Radius.
        /// </summary>
        internal static string SensorExpanded {
            get {
                return ResourceManager.GetString("SensorExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Scanner.
        /// </summary>
        internal static string SensorFastScan {
            get {
                return ResourceManager.GetString("SensorFastScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Weight Scanner.
        /// </summary>
        internal static string SensorLightWeight {
            get {
                return ResourceManager.GetString("SensorLightWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-Range Scanner.
        /// </summary>
        internal static string SensorLongRange {
            get {
                return ResourceManager.GetString("SensorLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide Angle Scanner.
        /// </summary>
        internal static string SensorWideAngle {
            get {
                return ResourceManager.GetString("SensorWideAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast Resistant Shield Booster.
        /// </summary>
        internal static string ShieldBoosterExplosive {
            get {
                return ResourceManager.GetString("ShieldBoosterExplosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Duty Shield Booster.
        /// </summary>
        internal static string ShieldBoosterHeavyDuty {
            get {
                return ResourceManager.GetString("ShieldBoosterHeavyDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinetic Resistant Shield Booster.
        /// </summary>
        internal static string ShieldBoosterKinetic {
            get {
                return ResourceManager.GetString("ShieldBoosterKinetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance Augmented Shield Booster.
        /// </summary>
        internal static string ShieldBoosterResistive {
            get {
                return ResourceManager.GetString("ShieldBoosterResistive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Resistant Shield Booster.
        /// </summary>
        internal static string ShieldBoosterThermic {
            get {
                return ResourceManager.GetString("ShieldBoosterThermic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Charge Shield Cell Bank.
        /// </summary>
        internal static string ShieldCellBankRapid {
            get {
                return ResourceManager.GetString("ShieldCellBankRapid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialised Shield Cell Bank.
        /// </summary>
        internal static string ShieldCellBankSpecialised {
            get {
                return ResourceManager.GetString("ShieldCellBankSpecialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinetic Resistant Shields.
        /// </summary>
        internal static string ShieldGeneratorKinetic {
            get {
                return ResourceManager.GetString("ShieldGeneratorKinetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced, Low Power Shields.
        /// </summary>
        internal static string ShieldGeneratorOptimised {
            get {
                return ResourceManager.GetString("ShieldGeneratorOptimised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforced Shields.
        /// </summary>
        internal static string ShieldGeneratorReinforced {
            get {
                return ResourceManager.GetString("ShieldGeneratorReinforced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Resistant Shields.
        /// </summary>
        internal static string ShieldGeneratorThermic {
            get {
                return ResourceManager.GetString("ShieldGeneratorThermic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Wake Scanner.
        /// </summary>
        internal static string WakeScannerFastScan {
            get {
                return ResourceManager.GetString("WakeScannerFastScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Weight Wake Scanner.
        /// </summary>
        internal static string WakeScannerLightWeight {
            get {
                return ResourceManager.GetString("WakeScannerLightWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-Range Wake Scanner.
        /// </summary>
        internal static string WakeScannerLongRange {
            get {
                return ResourceManager.GetString("WakeScannerLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforced Wake Scanner.
        /// </summary>
        internal static string WakeScannerReinforced {
            get {
                return ResourceManager.GetString("WakeScannerReinforced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shielded Wake Scanner.
        /// </summary>
        internal static string WakeScannerShielded {
            get {
                return ResourceManager.GetString("WakeScannerShielded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide Angle Wake Scanner.
        /// </summary>
        internal static string WakeScannerWideAngle {
            get {
                return ResourceManager.GetString("WakeScannerWideAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Shot.
        /// </summary>
        internal static string WeaponDoubleShot {
            get {
                return ResourceManager.GetString("WeaponDoubleShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient Weapon.
        /// </summary>
        internal static string WeaponEfficient {
            get {
                return ResourceManager.GetString("WeaponEfficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focused Weapon.
        /// </summary>
        internal static string WeaponFocused {
            get {
                return ResourceManager.GetString("WeaponFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Capacity Magazine.
        /// </summary>
        internal static string WeaponHighCapacity {
            get {
                return ResourceManager.GetString("WeaponHighCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Weight Mount.
        /// </summary>
        internal static string WeaponLightWeight {
            get {
                return ResourceManager.GetString("WeaponLightWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-Range Weapon.
        /// </summary>
        internal static string WeaponLongRange {
            get {
                return ResourceManager.GetString("WeaponLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcharged Weapon.
        /// </summary>
        internal static string WeaponOvercharged {
            get {
                return ResourceManager.GetString("WeaponOvercharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Fire Modification.
        /// </summary>
        internal static string WeaponRapidFire {
            get {
                return ResourceManager.GetString("WeaponRapidFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-Range Blaster.
        /// </summary>
        internal static string WeaponShortRange {
            get {
                return ResourceManager.GetString("WeaponShortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sturdy Mount.
        /// </summary>
        internal static string WeaponSturdy {
            get {
                return ResourceManager.GetString("WeaponSturdy", resourceCulture);
            }
        }
    }
}
