//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrganicSpeciesCond {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrganicSpeciesCond() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.OrganicSpeciesCond", typeof(OrganicSpeciesCond).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and Seemingly more common near galactic core..
        /// </summary>
        public static string AlbidumSinuousTubers {
            get {
                return ResourceManager.GetString("AlbidumSinuousTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, a temperature range of 175 to 180 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string AleoidaArcus {
            get {
                return ResourceManager.GetString("AleoidaArcus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, a temperature range of 180 to 190 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string AleoidaCoronamus {
            get {
                return ResourceManager.GetString("AleoidaCoronamus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, a temperature range of 190 to 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string AleoidaGravis {
            get {
                return ResourceManager.GetString("AleoidaGravis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string AleoidaLaminiae {
            get {
                return ResourceManager.GetString("AleoidaLaminiae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string AleoidaSpica {
            get {
                return ResourceManager.GetString("AleoidaSpica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Metal Rich planet with an A type star, and None atmosphere. Additionally An Earth-Like, Ammonia, water giant or Gas Giant with water or ammonia based life must be present in system...
        /// </summary>
        public static string AmphoraPlant {
            get {
                return ResourceManager.GetString("AmphoraPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and near system with Guardian ruins..
        /// </summary>
        public static string AureumBrainTree {
            get {
                return ResourceManager.GetString("AureumBrainTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Neon,NeonRich atmosphere..
        /// </summary>
        public static string BacteriumAcies {
            get {
                return ResourceManager.GetString("BacteriumAcies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Ammonia atmosphere..
        /// </summary>
        public static string BacteriumAlcyoneum {
            get {
                return ResourceManager.GetString("BacteriumAlcyoneum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a CarbonDioxide atmosphere..
        /// </summary>
        public static string BacteriumAurasus {
            get {
                return ResourceManager.GetString("BacteriumAurasus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Methane,MethaneRich atmosphere..
        /// </summary>
        public static string BacteriumBullaris {
            get {
                return ResourceManager.GetString("BacteriumBullaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Water,SulphurDioxide atmosphere..
        /// </summary>
        public static string BacteriumCerbrus {
            get {
                return ResourceManager.GetString("BacteriumCerbrus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Nitrogen atmosphere..
        /// </summary>
        public static string BacteriumInformem {
            get {
                return ResourceManager.GetString("BacteriumInformem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Helium atmosphere..
        /// </summary>
        public static string BacteriumNebulus {
            get {
                return ResourceManager.GetString("BacteriumNebulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Neon,NeonRich atmosphere and Nitrogen,Ammonia volcanism..
        /// </summary>
        public static string BacteriumOmentum {
            get {
                return ResourceManager.GetString("BacteriumOmentum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Neon,NeonRich atmosphere and Carbon,Methane volcanism..
        /// </summary>
        public static string BacteriumScopulum {
            get {
                return ResourceManager.GetString("BacteriumScopulum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with Helium,Iron,Silicate,Ammonia volcanism..
        /// </summary>
        public static string BacteriumTela {
            get {
                return ResourceManager.GetString("BacteriumTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Neon,NeonRich atmosphere and Water volcanism..
        /// </summary>
        public static string BacteriumVerrata {
            get {
                return ResourceManager.GetString("BacteriumVerrata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Argon atmosphere..
        /// </summary>
        public static string BacteriumVesicula {
            get {
                return ResourceManager.GetString("BacteriumVesicula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a Oxygen atmosphere..
        /// </summary>
        public static string BacteriumVolu {
            get {
                return ResourceManager.GetString("BacteriumVolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere, and In or &lt;150 light years from a nebula..
        /// </summary>
        public static string BarkMounds {
            get {
                return ResourceManager.GetString("BarkMounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an O,B,A type star, and SulphurDioxide,None atmosphere..
        /// </summary>
        public static string BlatteumBioluminescentAnemone {
            get {
                return ResourceManager.GetString("BlatteumBioluminescentAnemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and Seemingly more common near galactic core..
        /// </summary>
        public static string BlatteumSinuousTubers {
            get {
                return ResourceManager.GetString("BlatteumSinuousTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, a temperature range of 180 to 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string CactoidaCortexum {
            get {
                return ResourceManager.GetString("CactoidaCortexum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Ammonia atmosphere. Unofficially, additional sources say  this is also known as Tetonus aymericus..
        /// </summary>
        public static string CactoidaLapis {
            get {
                return ResourceManager.GetString("CactoidaLapis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string CactoidaPeperatis {
            get {
                return ResourceManager.GetString("CactoidaPeperatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and a temperature range of 180 to 195..
        /// </summary>
        public static string CactoidaPullulanta {
            get {
                return ResourceManager.GetString("CactoidaPullulanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Water atmosphere..
        /// </summary>
        public static string CactoidaVermis {
            get {
                return ResourceManager.GetString("CactoidaVermis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and Seemingly more common near galactic core..
        /// </summary>
        public static string CaeruleumSinuousTubers {
            get {
                return ResourceManager.GetString("CaeruleumSinuousTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content planet with a maximum gravity of 0.27, a temperature greater than 190 kelvin, and Water,CarbonDioxide atmosphere..
        /// </summary>
        public static string ClypeusLacrimam {
            get {
                return ResourceManager.GetString("ClypeusLacrimam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content planet with a maximum gravity of 0.27, a temperature greater than 190 kelvin, and Water,CarbonDioxide atmosphere..
        /// </summary>
        public static string ClypeusMargaritus {
            get {
                return ResourceManager.GetString("ClypeusMargaritus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content planet with a maximum gravity of 0.27, a temperature greater than 190 kelvin, and Water,CarbonDioxide atmosphere..
        /// </summary>
        public static string ClypeusSpeculumi {
            get {
                return ResourceManager.GetString("ClypeusSpeculumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string ConchaAureolas {
            get {
                return ResourceManager.GetString("ConchaAureolas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Nitrogen atmosphere..
        /// </summary>
        public static string ConchaBiconcavis {
            get {
                return ResourceManager.GetString("ConchaBiconcavis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and CarbonDioxide atmosphere..
        /// </summary>
        public static string ConchaLabiata {
            get {
                return ResourceManager.GetString("ConchaLabiata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, a temperature range of 180 to 195 kelvin, and Water,CarbonDioxide atmosphere..
        /// </summary>
        public static string ConchaRenibus {
            get {
                return ResourceManager.GetString("ConchaRenibus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an O,B,A type star, and SulphurDioxide,None atmosphere..
        /// </summary>
        public static string CroceumAnemone {
            get {
                return ResourceManager.GetString("CroceumAnemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an A,Neutron type star, a temperature range of 0 to 273 kelvin, and None atmosphere. Additionally An Earth-Like, Ammonia, water giant or Gas Giant with water or ammonia based life must be present in system and must be &gt;12000 light seconds from the nearest star..
        /// </summary>
        public static string CrystallineShards {
            get {
                return ResourceManager.GetString("CrystallineShards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy planet with a maximum gravity of 0.27, an A,Neutron type star, and Helium,Neon,Argon atmosphere..
        /// </summary>
        public static string ElectricaePluma {
            get {
                return ResourceManager.GetString("ElectricaePluma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy planet with a maximum gravity of 0.27, an A,Neutron type star, and Helium,Neon,Argon atmosphere..
        /// </summary>
        public static string ElectricaeRadialem {
            get {
                return ResourceManager.GetString("ElectricaeRadialem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky planet with a maximum gravity of 0.27, and Argon atmosphere..
        /// </summary>
        public static string FonticuluaCampestris {
            get {
                return ResourceManager.GetString("FonticuluaCampestris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky planet with a maximum gravity of 0.27, and Methane,MethaneRich atmosphere..
        /// </summary>
        public static string FonticuluaDigitos {
            get {
                return ResourceManager.GetString("FonticuluaDigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky planet with a maximum gravity of 0.27, and Oxygen atmosphere..
        /// </summary>
        public static string FonticuluaFluctus {
            get {
                return ResourceManager.GetString("FonticuluaFluctus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky planet with a maximum gravity of 0.27, and Nitrogen atmosphere..
        /// </summary>
        public static string FonticuluaLapida {
            get {
                return ResourceManager.GetString("FonticuluaLapida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky planet with a maximum gravity of 0.27, and Neon,NeonRich atmosphere..
        /// </summary>
        public static string FonticuluaSegmentatus {
            get {
                return ResourceManager.GetString("FonticuluaSegmentatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky planet with a maximum gravity of 0.27, and ArgonRich atmosphere..
        /// </summary>
        public static string FonticuluaUpupam {
            get {
                return ResourceManager.GetString("FonticuluaUpupam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature less than 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string FrutexaAcus {
            get {
                return ResourceManager.GetString("FrutexaAcus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and SulphurDioxide atmosphere..
        /// </summary>
        public static string FrutexaCollum {
            get {
                return ResourceManager.GetString("FrutexaCollum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature less than 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string FrutexaFera {
            get {
                return ResourceManager.GetString("FrutexaFera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string FrutexaFlabellum {
            get {
                return ResourceManager.GetString("FrutexaFlabellum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string FrutexaFlammasis {
            get {
                return ResourceManager.GetString("FrutexaFlammasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a High Metal Content planet with a maximum gravity of 0.27, a temperature less than 195 kelvin, and CarbonDioxide,Ammonia atmosphere..
        /// </summary>
        public static string FrutexaMetallicum {
            get {
                return ResourceManager.GetString("FrutexaMetallicum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and Water atmosphere..
        /// </summary>
        public static string FrutexaSponsae {
            get {
                return ResourceManager.GetString("FrutexaSponsae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky Ice planet with a maximum gravity of 0.27, Any atmosphere, and Water volcanism..
        /// </summary>
        public static string FumerolaAquatis {
            get {
                return ResourceManager.GetString("FumerolaAquatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky Ice planet with a maximum gravity of 0.27, Any atmosphere, and Carbon,Methane volcanism..
        /// </summary>
        public static string FumerolaCarbosis {
            get {
                return ResourceManager.GetString("FumerolaCarbosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content planet with a maximum gravity of 0.27, Any atmosphere, and Silicate,Iron,Rocky volcanism..
        /// </summary>
        public static string FumerolaExtremus {
            get {
                return ResourceManager.GetString("FumerolaExtremus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky Ice planet with a maximum gravity of 0.27, Any atmosphere, and Nitrogen,Ammonia volcanism..
        /// </summary>
        public static string FumerolaNitris {
            get {
                return ResourceManager.GetString("FumerolaNitris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Argon,ArgonRich atmosphere..
        /// </summary>
        public static string FungoidaBullarum {
            get {
                return ResourceManager.GetString("FungoidaBullarum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Water,CarbonDioxide atmosphere. Additionally, Carbon Dioxide atmospheres requires a temperature range of 180 to 195 kelvin..
        /// </summary>
        public static string FungoidaGelata {
            get {
                return ResourceManager.GetString("FungoidaGelata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Ammonia,Methane atmosphere..
        /// </summary>
        public static string FungoidaSetisis {
            get {
                return ResourceManager.GetString("FungoidaSetisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and Water,CarbonDioxide atmosphere..
        /// </summary>
        public static string FungoidaStabitis {
            get {
                return ResourceManager.GetString("FungoidaStabitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and near system with Guardian ruins..
        /// </summary>
        public static string GypseeumBrainTree {
            get {
                return ResourceManager.GetString("GypseeumBrainTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and near system with Guardian ruins..
        /// </summary>
        public static string LindigoticumBrainTree {
            get {
                return ResourceManager.GetString("LindigoticumBrainTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and Seemingly more common near galactic core..
        /// </summary>
        public static string LindigoticumSinuousTubers {
            get {
                return ResourceManager.GetString("LindigoticumSinuousTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and near system with Guardian ruins..
        /// </summary>
        public static string LividumBrainTree {
            get {
                return ResourceManager.GetString("LividumBrainTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an O,B,A type star, and SulphurDioxide,None atmosphere..
        /// </summary>
        public static string LuteolumAnemone {
            get {
                return ResourceManager.GetString("LuteolumAnemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content planet with a maximum gravity of 0.27, a temperature range of 180 to 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string OsseusCornibus {
            get {
                return ResourceManager.GetString("OsseusCornibus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content planet with a maximum gravity of 0.27, and Water atmosphere..
        /// </summary>
        public static string OsseusDiscus {
            get {
                return ResourceManager.GetString("OsseusDiscus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, a temperature range of 180 to 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string OsseusFractus {
            get {
                return ResourceManager.GetString("OsseusFractus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, a temperature range of 180 to 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string OsseusPellebantus {
            get {
                return ResourceManager.GetString("OsseusPellebantus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content,Rocky Ice planet with a maximum gravity of 0.27, and Argon,Methane,Nitrogen atmosphere..
        /// </summary>
        public static string OsseusPumice {
            get {
                return ResourceManager.GetString("OsseusPumice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string OsseusSpiralis {
            get {
                return ResourceManager.GetString("OsseusSpiralis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and near system with Guardian ruins..
        /// </summary>
        public static string OstrinumBrainTree {
            get {
                return ResourceManager.GetString("OstrinumBrainTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an O,B,A type star, and SulphurDioxide,None atmosphere..
        /// </summary>
        public static string PrasinumBioluminescentAnemone {
            get {
                return ResourceManager.GetString("PrasinumBioluminescentAnemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and Seemingly more common near galactic core..
        /// </summary>
        public static string PrasinumSinuousTubers {
            get {
                return ResourceManager.GetString("PrasinumSinuousTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an O,B,A type star, and SulphurDioxide,None atmosphere..
        /// </summary>
        public static string PuniceumAnemone {
            get {
                return ResourceManager.GetString("PuniceumAnemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and near system with Guardian ruins..
        /// </summary>
        public static string PuniceumBrainTree {
            get {
                return ResourceManager.GetString("PuniceumBrainTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Icy,Rocky Ice planet with a maximum gravity of 0.27, and SulphurDioxide atmosphere..
        /// </summary>
        public static string ReceptaConditivus {
            get {
                return ResourceManager.GetString("ReceptaConditivus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky,High Metal Content planet with a maximum gravity of 0.27, and SulphurDioxide atmosphere..
        /// </summary>
        public static string ReceptaDeltahedronix {
            get {
                return ResourceManager.GetString("ReceptaDeltahedronix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a maximum gravity of 0.27, and SulphurDioxide atmosphere..
        /// </summary>
        public static string ReceptaUmbrux {
            get {
                return ResourceManager.GetString("ReceptaUmbrux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an O,B,A type star, and SulphurDioxide,None atmosphere..
        /// </summary>
        public static string RoseumAnemone {
            get {
                return ResourceManager.GetString("RoseumAnemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an O,B,A type star, and SulphurDioxide,None atmosphere..
        /// </summary>
        public static string RoseumBioluminescentAnemone {
            get {
                return ResourceManager.GetString("RoseumBioluminescentAnemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and near system with Guardian ruins..
        /// </summary>
        public static string RoseumBrainTree {
            get {
                return ResourceManager.GetString("RoseumBrainTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and Seemingly more common near galactic core..
        /// </summary>
        public static string RoseumSinuousTubers {
            get {
                return ResourceManager.GetString("RoseumSinuousTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with an  type star, and SulphurDioxide,None atmosphere..
        /// </summary>
        public static string RubeumBioluminescentAnemone {
            get {
                return ResourceManager.GetString("RubeumBioluminescentAnemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a temperature greater than 165 kelvin, and SulphurDioxide atmosphere..
        /// </summary>
        public static string StratumAraneamus {
            get {
                return ResourceManager.GetString("StratumAraneamus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a temperature greater than 190 kelvin, and SulphurDioxide,CarbonDioxide atmosphere..
        /// </summary>
        public static string StratumCucumisis {
            get {
                return ResourceManager.GetString("StratumCucumisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a temperature range of 165 to 190 kelvin, and SulphurDioxide,CarbonDioxide atmosphere..
        /// </summary>
        public static string StratumExcutitus {
            get {
                return ResourceManager.GetString("StratumExcutitus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a temperature greater than 190 kelvin, and SulphurDioxide,CarbonDioxide atmosphere..
        /// </summary>
        public static string StratumFrigus {
            get {
                return ResourceManager.GetString("StratumFrigus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a temperature greater than 165 kelvin, and Ammonia atmosphere..
        /// </summary>
        public static string StratumLaminamus {
            get {
                return ResourceManager.GetString("StratumLaminamus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a temperature range of 165 to 190 kelvin, and SulphurDioxide,CarbonDioxide atmosphere..
        /// </summary>
        public static string StratumLimaxus {
            get {
                return ResourceManager.GetString("StratumLimaxus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a temperature greater than 165 kelvin, and Ammonia,Water,CarbonDioxide atmosphere..
        /// </summary>
        public static string StratumPaleas {
            get {
                return ResourceManager.GetString("StratumPaleas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a High Metal Content planet with a temperature greater than 165 kelvin, and AnyThin atmosphere..
        /// </summary>
        public static string StratumTectonicas {
            get {
                return ResourceManager.GetString("StratumTectonicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.15, a temperature range of 160 to 190 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TubusCavas {
            get {
                return ResourceManager.GetString("TubusCavas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.15, a temperature range of 160 to 190 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TubusCompagibus {
            get {
                return ResourceManager.GetString("TubusCompagibus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.15, a temperature range of 160 to 190 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TubusConifer {
            get {
                return ResourceManager.GetString("TubusConifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.15, a temperature greater than 160 kelvin, and Ammonia atmosphere..
        /// </summary>
        public static string TubusRosarium {
            get {
                return ResourceManager.GetString("TubusRosarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a High Metal Content planet with a maximum gravity of 0.15, a temperature range of 160 to 190 kelvin, and CarbonDioxide,Ammonia atmosphere..
        /// </summary>
        public static string TubusSororibus {
            get {
                return ResourceManager.GetString("TubusSororibus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature range of 175 to 180 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockAlbata {
            get {
                return ResourceManager.GetString("TussockAlbata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and Argon,Methane atmosphere..
        /// </summary>
        public static string TussockCapillum {
            get {
                return ResourceManager.GetString("TussockCapillum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature range of 180 to 190 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockCaputus {
            get {
                return ResourceManager.GetString("TussockCaputus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string TussockCatena {
            get {
                return ResourceManager.GetString("TussockCatena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string TussockCultro {
            get {
                return ResourceManager.GetString("TussockCultro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and Ammonia atmosphere..
        /// </summary>
        public static string TussockDivisa {
            get {
                return ResourceManager.GetString("TussockDivisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature range of 160 to 170 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockIgnis {
            get {
                return ResourceManager.GetString("TussockIgnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature range of 145 to 155 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockPennata {
            get {
                return ResourceManager.GetString("TussockPennata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature less than 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockPennatis {
            get {
                return ResourceManager.GetString("TussockPennatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature less than 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockPropagito {
            get {
                return ResourceManager.GetString("TussockPropagito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature range of 170 to 175 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockSerrati {
            get {
                return ResourceManager.GetString("TussockSerrati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and SulphurDioxide atmosphere..
        /// </summary>
        public static string TussockStigmasis {
            get {
                return ResourceManager.GetString("TussockStigmasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature range of 190 to 195 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockTriticum {
            get {
                return ResourceManager.GetString("TussockTriticum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, a temperature range of 155 to 160 kelvin, and CarbonDioxide atmosphere..
        /// </summary>
        public static string TussockVentusa {
            get {
                return ResourceManager.GetString("TussockVentusa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a Rocky planet with a maximum gravity of 0.27, and Water atmosphere..
        /// </summary>
        public static string TussockVirgam {
            get {
                return ResourceManager.GetString("TussockVirgam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and Seemingly more common near galactic core..
        /// </summary>
        public static string ViolaceumSinuousTubers {
            get {
                return ResourceManager.GetString("ViolaceumSinuousTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and near system with Guardian ruins..
        /// </summary>
        public static string VirideBrainTree {
            get {
                return ResourceManager.GetString("VirideBrainTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This species requires a planet with a None atmosphere and Any volcanism, and Seemingly more common near galactic core..
        /// </summary>
        public static string VirideSinuousTubers {
            get {
                return ResourceManager.GetString("VirideSinuousTubers", resourceCulture);
            }
        }
    }
}
