//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrganicSpecies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrganicSpecies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.OrganicSpecies", typeof(OrganicSpecies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcus.
        /// </summary>
        public static string Aleoids_01 {
            get {
                return ResourceManager.GetString("Aleoids_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronamus.
        /// </summary>
        public static string Aleoids_02 {
            get {
                return ResourceManager.GetString("Aleoids_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spica.
        /// </summary>
        public static string Aleoids_03 {
            get {
                return ResourceManager.GetString("Aleoids_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminiae.
        /// </summary>
        public static string Aleoids_04 {
            get {
                return ResourceManager.GetString("Aleoids_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravis.
        /// </summary>
        public static string Aleoids_05 {
            get {
                return ResourceManager.GetString("Aleoids_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurasus.
        /// </summary>
        public static string Bacterial_01 {
            get {
                return ResourceManager.GetString("Bacterial_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebulus.
        /// </summary>
        public static string Bacterial_02 {
            get {
                return ResourceManager.GetString("Bacterial_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scopulum.
        /// </summary>
        public static string Bacterial_03 {
            get {
                return ResourceManager.GetString("Bacterial_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acies.
        /// </summary>
        public static string Bacterial_04 {
            get {
                return ResourceManager.GetString("Bacterial_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vesicula.
        /// </summary>
        public static string Bacterial_05 {
            get {
                return ResourceManager.GetString("Bacterial_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcyoneum.
        /// </summary>
        public static string Bacterial_06 {
            get {
                return ResourceManager.GetString("Bacterial_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela.
        /// </summary>
        public static string Bacterial_07 {
            get {
                return ResourceManager.GetString("Bacterial_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informem.
        /// </summary>
        public static string Bacterial_08 {
            get {
                return ResourceManager.GetString("Bacterial_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volu.
        /// </summary>
        public static string Bacterial_09 {
            get {
                return ResourceManager.GetString("Bacterial_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullaris.
        /// </summary>
        public static string Bacterial_10 {
            get {
                return ResourceManager.GetString("Bacterial_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omentum.
        /// </summary>
        public static string Bacterial_11 {
            get {
                return ResourceManager.GetString("Bacterial_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerbrus.
        /// </summary>
        public static string Bacterial_12 {
            get {
                return ResourceManager.GetString("Bacterial_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verrata.
        /// </summary>
        public static string Bacterial_13 {
            get {
                return ResourceManager.GetString("Bacterial_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortexum.
        /// </summary>
        public static string Cactoid_01 {
            get {
                return ResourceManager.GetString("Cactoid_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lapis.
        /// </summary>
        public static string Cactoid_02 {
            get {
                return ResourceManager.GetString("Cactoid_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vermis.
        /// </summary>
        public static string Cactoid_03 {
            get {
                return ResourceManager.GetString("Cactoid_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pullulanta.
        /// </summary>
        public static string Cactoid_04 {
            get {
                return ResourceManager.GetString("Cactoid_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peperatis.
        /// </summary>
        public static string Cactoid_05 {
            get {
                return ResourceManager.GetString("Cactoid_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lacrimam.
        /// </summary>
        public static string Clypeus_01 {
            get {
                return ResourceManager.GetString("Clypeus_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margaritus.
        /// </summary>
        public static string Clypeus_02 {
            get {
                return ResourceManager.GetString("Clypeus_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speculumi.
        /// </summary>
        public static string Clypeus_03 {
            get {
                return ResourceManager.GetString("Clypeus_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renibus.
        /// </summary>
        public static string Conchas_01 {
            get {
                return ResourceManager.GetString("Conchas_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aureolas.
        /// </summary>
        public static string Conchas_02 {
            get {
                return ResourceManager.GetString("Conchas_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labiata.
        /// </summary>
        public static string Conchas_03 {
            get {
                return ResourceManager.GetString("Conchas_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biconcavis.
        /// </summary>
        public static string Conchas_04 {
            get {
                return ResourceManager.GetString("Conchas_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bark Mounds.
        /// </summary>
        public static string Cone {
            get {
                return ResourceManager.GetString("Cone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pluma.
        /// </summary>
        public static string Electricae_01 {
            get {
                return ResourceManager.GetString("Electricae_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radialem.
        /// </summary>
        public static string Electricae_02 {
            get {
                return ResourceManager.GetString("Electricae_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentatus.
        /// </summary>
        public static string Fonticulus_01 {
            get {
                return ResourceManager.GetString("Fonticulus_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campestris.
        /// </summary>
        public static string Fonticulus_02 {
            get {
                return ResourceManager.GetString("Fonticulus_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upupam.
        /// </summary>
        public static string Fonticulus_03 {
            get {
                return ResourceManager.GetString("Fonticulus_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lapida.
        /// </summary>
        public static string Fonticulus_04 {
            get {
                return ResourceManager.GetString("Fonticulus_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluctus.
        /// </summary>
        public static string Fonticulus_05 {
            get {
                return ResourceManager.GetString("Fonticulus_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitos.
        /// </summary>
        public static string Fonticulus_06 {
            get {
                return ResourceManager.GetString("Fonticulus_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbosis.
        /// </summary>
        public static string Fumerolas_01 {
            get {
                return ResourceManager.GetString("Fumerolas_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremus.
        /// </summary>
        public static string Fumerolas_02 {
            get {
                return ResourceManager.GetString("Fumerolas_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitris.
        /// </summary>
        public static string Fumerolas_03 {
            get {
                return ResourceManager.GetString("Fumerolas_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatis.
        /// </summary>
        public static string Fumerolas_04 {
            get {
                return ResourceManager.GetString("Fumerolas_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setisis.
        /// </summary>
        public static string Fungoids_01 {
            get {
                return ResourceManager.GetString("Fungoids_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabitis.
        /// </summary>
        public static string Fungoids_02 {
            get {
                return ResourceManager.GetString("Fungoids_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullarum.
        /// </summary>
        public static string Fungoids_03 {
            get {
                return ResourceManager.GetString("Fungoids_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelata.
        /// </summary>
        public static string Fungoids_04 {
            get {
                return ResourceManager.GetString("Fungoids_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalline Shards.
        /// </summary>
        public static string Ground_Struct_Ice {
            get {
                return ResourceManager.GetString("Ground_Struct_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radicoida Unica.
        /// </summary>
        public static string Ingensradices_Unicus {
            get {
                return ResourceManager.GetString("Ingensradices_Unicus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        public static string L_Cry_IcCry {
            get {
                return ResourceManager.GetString("L_Cry_IcCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic.
        /// </summary>
        public static string L_Cry_MetCry {
            get {
                return ResourceManager.GetString("L_Cry_MetCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silicate.
        /// </summary>
        public static string L_Cry_QtzCry {
            get {
                return ResourceManager.GetString("L_Cry_QtzCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parasol.
        /// </summary>
        public static string L_Org_Moll03_V1 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parasol.
        /// </summary>
        public static string L_Org_Moll03_V11 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parasol.
        /// </summary>
        public static string L_Org_Moll03_V12 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb.
        /// </summary>
        public static string L_Org_Moll03_V2 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb.
        /// </summary>
        public static string L_Org_Moll03_V21 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb.
        /// </summary>
        public static string L_Org_Moll03_V22 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella.
        /// </summary>
        public static string L_Org_Moll03_V3 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella.
        /// </summary>
        public static string L_Org_Moll03_V31 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella.
        /// </summary>
        public static string L_Org_Moll03_V32 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capsule.
        /// </summary>
        public static string L_Org_Moll03_V4 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capsule.
        /// </summary>
        public static string L_Org_Moll03_V41 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capsule.
        /// </summary>
        public static string L_Org_Moll03_V42 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reel.
        /// </summary>
        public static string L_Org_Moll03_V6 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reel.
        /// </summary>
        public static string L_Org_Moll03_V61 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reel.
        /// </summary>
        public static string L_Org_Moll03_V62 {
            get {
                return ResourceManager.GetString("L_Org_Moll03_V62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcite.
        /// </summary>
        public static string L_Org_PltFun_V1 {
            get {
                return ResourceManager.GetString("L_Org_PltFun_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcite.
        /// </summary>
        public static string L_Org_PltFun_V11 {
            get {
                return ResourceManager.GetString("L_Org_PltFun_V11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcite.
        /// </summary>
        public static string L_Org_PltFun_V12 {
            get {
                return ResourceManager.GetString("L_Org_PltFun_V12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcite.
        /// </summary>
        public static string L_Org_PltFun_V13 {
            get {
                return ResourceManager.GetString("L_Org_PltFun_V13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string L_Seed_Pln01_V1 {
            get {
                return ResourceManager.GetString("L_Seed_Pln01_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string L_Seed_Pln01_V11 {
            get {
                return ResourceManager.GetString("L_Seed_Pln01_V11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string L_Seed_Pln01_V12 {
            get {
                return ResourceManager.GetString("L_Seed_Pln01_V12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string L_Seed_Pln01_V13 {
            get {
                return ResourceManager.GetString("L_Seed_Pln01_V13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string L_Seed_Pln01_V14 {
            get {
                return ResourceManager.GetString("L_Seed_Pln01_V14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster.
        /// </summary>
        public static string L_Seed_Pln02_V3 {
            get {
                return ResourceManager.GetString("L_Seed_Pln02_V3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster.
        /// </summary>
        public static string L_Seed_Pln02_V31 {
            get {
                return ResourceManager.GetString("L_Seed_Pln02_V31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster.
        /// </summary>
        public static string L_Seed_Pln02_V32 {
            get {
                return ResourceManager.GetString("L_Seed_Pln02_V32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stolon.
        /// </summary>
        public static string L_Seed_SdRt02 {
            get {
                return ResourceManager.GetString("L_Seed_SdRt02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractus.
        /// </summary>
        public static string Osseus_01 {
            get {
                return ResourceManager.GetString("Osseus_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discus.
        /// </summary>
        public static string Osseus_02 {
            get {
                return ResourceManager.GetString("Osseus_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiralis.
        /// </summary>
        public static string Osseus_03 {
            get {
                return ResourceManager.GetString("Osseus_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice.
        /// </summary>
        public static string Osseus_04 {
            get {
                return ResourceManager.GetString("Osseus_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornibus.
        /// </summary>
        public static string Osseus_05 {
            get {
                return ResourceManager.GetString("Osseus_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pellebantus.
        /// </summary>
        public static string Osseus_06 {
            get {
                return ResourceManager.GetString("Osseus_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrux.
        /// </summary>
        public static string Recepta_01 {
            get {
                return ResourceManager.GetString("Recepta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltahedronix.
        /// </summary>
        public static string Recepta_02 {
            get {
                return ResourceManager.GetString("Recepta_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditivus.
        /// </summary>
        public static string Recepta_03 {
            get {
                return ResourceManager.GetString("Recepta_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string S_Seed_SdTp01 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string S_Seed_SdTp011 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string S_Seed_SdTp012 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string S_Seed_SdTp013 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peduncle.
        /// </summary>
        public static string S_Seed_SdTp014 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster.
        /// </summary>
        public static string S_Seed_SdTp02 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster.
        /// </summary>
        public static string S_Seed_SdTp021 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster.
        /// </summary>
        public static string S_Seed_SdTp022 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster.
        /// </summary>
        public static string S_Seed_SdTp023 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster.
        /// </summary>
        public static string S_Seed_SdTp024 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octahedral.
        /// </summary>
        public static string S_Seed_SdTp03 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octahedral.
        /// </summary>
        public static string S_Seed_SdTp031 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octahedral.
        /// </summary>
        public static string S_Seed_SdTp032 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octahedral.
        /// </summary>
        public static string S_Seed_SdTp033 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octahedral.
        /// </summary>
        public static string S_Seed_SdTp034 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collared.
        /// </summary>
        public static string S_Seed_SdTp04 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collared.
        /// </summary>
        public static string S_Seed_SdTp041 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collared.
        /// </summary>
        public static string S_Seed_SdTp042 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collared.
        /// </summary>
        public static string S_Seed_SdTp043 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalice.
        /// </summary>
        public static string S_Seed_SdTp05 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalice.
        /// </summary>
        public static string S_Seed_SdTp051 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalice.
        /// </summary>
        public static string S_Seed_SdTp052 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalice.
        /// </summary>
        public static string S_Seed_SdTp053 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalice.
        /// </summary>
        public static string S_Seed_SdTp054 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyre.
        /// </summary>
        public static string S_Seed_SdTp06 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyre.
        /// </summary>
        public static string S_Seed_SdTp061 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhizome.
        /// </summary>
        public static string S_Seed_SdTp07 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhizome.
        /// </summary>
        public static string S_Seed_SdTp071 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhizome.
        /// </summary>
        public static string S_Seed_SdTp072 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhizome.
        /// </summary>
        public static string S_Seed_SdTp073 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhizome.
        /// </summary>
        public static string S_Seed_SdTp074 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadripartite.
        /// </summary>
        public static string S_Seed_SdTp08 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadripartite.
        /// </summary>
        public static string S_Seed_SdTp081 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadripartite.
        /// </summary>
        public static string S_Seed_SdTp082 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadripartite.
        /// </summary>
        public static string S_Seed_SdTp083 {
            get {
                return ResourceManager.GetString("S_Seed_SdTp083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roseum.
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gypseeum.
        /// </summary>
        public static string SeedABCD_01 {
            get {
                return ResourceManager.GetString("SeedABCD_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrinum.
        /// </summary>
        public static string SeedABCD_02 {
            get {
                return ResourceManager.GetString("SeedABCD_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viride.
        /// </summary>
        public static string SeedABCD_03 {
            get {
                return ResourceManager.GetString("SeedABCD_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lividum.
        /// </summary>
        public static string SeedEFGH {
            get {
                return ResourceManager.GetString("SeedEFGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aureum.
        /// </summary>
        public static string SeedEFGH_01 {
            get {
                return ResourceManager.GetString("SeedEFGH_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puniceum.
        /// </summary>
        public static string SeedEFGH_02 {
            get {
                return ResourceManager.GetString("SeedEFGH_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lindigoticum.
        /// </summary>
        public static string SeedEFGH_03 {
            get {
                return ResourceManager.GetString("SeedEFGH_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flabellum.
        /// </summary>
        public static string Shrubs_01 {
            get {
                return ResourceManager.GetString("Shrubs_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acus.
        /// </summary>
        public static string Shrubs_02 {
            get {
                return ResourceManager.GetString("Shrubs_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallicum.
        /// </summary>
        public static string Shrubs_03 {
            get {
                return ResourceManager.GetString("Shrubs_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flammasis.
        /// </summary>
        public static string Shrubs_04 {
            get {
                return ResourceManager.GetString("Shrubs_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fera.
        /// </summary>
        public static string Shrubs_05 {
            get {
                return ResourceManager.GetString("Shrubs_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsae.
        /// </summary>
        public static string Shrubs_06 {
            get {
                return ResourceManager.GetString("Shrubs_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collum.
        /// </summary>
        public static string Shrubs_07 {
            get {
                return ResourceManager.GetString("Shrubs_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourd.
        /// </summary>
        public static string Small_Org_Moll01_V1 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourd.
        /// </summary>
        public static string Small_Org_Moll01_V11 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourd.
        /// </summary>
        public static string Small_Org_Moll01_V12 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourd.
        /// </summary>
        public static string Small_Org_Moll01_V13 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourd.
        /// </summary>
        public static string Small_Org_Moll01_V14 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourd.
        /// </summary>
        public static string Small_Org_Moll01_V15 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourd.
        /// </summary>
        public static string Small_Org_Moll01_V16 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torus.
        /// </summary>
        public static string Small_Org_Moll01_V2 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torus.
        /// </summary>
        public static string Small_Org_Moll01_V21 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torus.
        /// </summary>
        public static string Small_Org_Moll01_V22 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torus.
        /// </summary>
        public static string Small_Org_Moll01_V23 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torus.
        /// </summary>
        public static string Small_Org_Moll01_V24 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squid.
        /// </summary>
        public static string Small_Org_Moll01_V3 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squid.
        /// </summary>
        public static string Small_Org_Moll01_V31 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squid.
        /// </summary>
        public static string Small_Org_Moll01_V32 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squid.
        /// </summary>
        public static string Small_Org_Moll01_V33 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squid.
        /// </summary>
        public static string Small_Org_Moll01_V34 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        public static string Small_Org_Moll01_V4 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        public static string Small_Org_Moll01_V41 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        public static string Small_Org_Moll01_V42 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        public static string Small_Org_Moll01_V43 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        public static string Small_Org_Moll01_V44 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe.
        /// </summary>
        public static string Small_Org_Moll01_V5 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe.
        /// </summary>
        public static string Small_Org_Moll01_V51 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe.
        /// </summary>
        public static string Small_Org_Moll01_V52 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe.
        /// </summary>
        public static string Small_Org_Moll01_V53 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe.
        /// </summary>
        public static string Small_Org_Moll01_V54 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe.
        /// </summary>
        public static string Small_Org_Moll01_V55 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe.
        /// </summary>
        public static string Small_Org_Moll01_V56 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell.
        /// </summary>
        public static string Small_Org_Moll01_V6 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell.
        /// </summary>
        public static string Small_Org_Moll01_V61 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell.
        /// </summary>
        public static string Small_Org_Moll01_V62 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell.
        /// </summary>
        public static string Small_Org_Moll01_V63 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell.
        /// </summary>
        public static string Small_Org_Moll01_V64 {
            get {
                return ResourceManager.GetString("Small_Org_Moll01_V64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luteolum.
        /// </summary>
        public static string Sphere {
            get {
                return ResourceManager.GetString("Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croceum.
        /// </summary>
        public static string SphereABCD_01 {
            get {
                return ResourceManager.GetString("SphereABCD_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puniceum.
        /// </summary>
        public static string SphereABCD_02 {
            get {
                return ResourceManager.GetString("SphereABCD_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roseum.
        /// </summary>
        public static string SphereABCD_03 {
            get {
                return ResourceManager.GetString("SphereABCD_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blatteum Bioluminescent.
        /// </summary>
        public static string SphereEFGH {
            get {
                return ResourceManager.GetString("SphereEFGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubeum Bioluminescent.
        /// </summary>
        public static string SphereEFGH_01 {
            get {
                return ResourceManager.GetString("SphereEFGH_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prasinum Bioluminescent.
        /// </summary>
        public static string SphereEFGH_02 {
            get {
                return ResourceManager.GetString("SphereEFGH_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roseum Bioluminescent.
        /// </summary>
        public static string SphereEFGH_03 {
            get {
                return ResourceManager.GetString("SphereEFGH_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral.
        /// </summary>
        public static string SPOI {
            get {
                return ResourceManager.GetString("SPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral.
        /// </summary>
        public static string SPOI_Ball {
            get {
                return ResourceManager.GetString("SPOI_Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stolon.
        /// </summary>
        public static string SPOI_Root {
            get {
                return ResourceManager.GetString("SPOI_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyre.
        /// </summary>
        public static string SPOI_SeedPolyp01 {
            get {
                return ResourceManager.GetString("SPOI_SeedPolyp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyre.
        /// </summary>
        public static string SPOI_SeedPolyp01_V1 {
            get {
                return ResourceManager.GetString("SPOI_SeedPolyp01_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string SPOI_SeedWeed01 {
            get {
                return ResourceManager.GetString("SPOI_SeedWeed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excutitus.
        /// </summary>
        public static string Stratum_01 {
            get {
                return ResourceManager.GetString("Stratum_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paleas.
        /// </summary>
        public static string Stratum_02 {
            get {
                return ResourceManager.GetString("Stratum_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminamus.
        /// </summary>
        public static string Stratum_03 {
            get {
                return ResourceManager.GetString("Stratum_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araneamus.
        /// </summary>
        public static string Stratum_04 {
            get {
                return ResourceManager.GetString("Stratum_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limaxus.
        /// </summary>
        public static string Stratum_05 {
            get {
                return ResourceManager.GetString("Stratum_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucumisis.
        /// </summary>
        public static string Stratum_06 {
            get {
                return ResourceManager.GetString("Stratum_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tectonicas.
        /// </summary>
        public static string Stratum_07 {
            get {
                return ResourceManager.GetString("Stratum_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigus.
        /// </summary>
        public static string Stratum_08 {
            get {
                return ResourceManager.GetString("Stratum_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barnacle.
        /// </summary>
        public static string Thargoid_Barnacle {
            get {
                return ResourceManager.GetString("Thargoid_Barnacle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barnacle.
        /// </summary>
        public static string Thargoid_Barnacle1 {
            get {
                return ResourceManager.GetString("Thargoid_Barnacle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barnacle.
        /// </summary>
        public static string Thargoid_Barnacle2 {
            get {
                return ResourceManager.GetString("Thargoid_Barnacle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous.
        /// </summary>
        public static string Tube {
            get {
                return ResourceManager.GetString("Tube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous.
        /// </summary>
        public static string TubeABCD_01 {
            get {
                return ResourceManager.GetString("TubeABCD_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous.
        /// </summary>
        public static string TubeABCD_02 {
            get {
                return ResourceManager.GetString("TubeABCD_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous.
        /// </summary>
        public static string TubeABCD_03 {
            get {
                return ResourceManager.GetString("TubeABCD_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous.
        /// </summary>
        public static string TubeEFGH {
            get {
                return ResourceManager.GetString("TubeEFGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous.
        /// </summary>
        public static string TubeEFGH_01 {
            get {
                return ResourceManager.GetString("TubeEFGH_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous.
        /// </summary>
        public static string TubeEFGH_02 {
            get {
                return ResourceManager.GetString("TubeEFGH_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous.
        /// </summary>
        public static string TubeEFGH_03 {
            get {
                return ResourceManager.GetString("TubeEFGH_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conifer.
        /// </summary>
        public static string Tubus_01 {
            get {
                return ResourceManager.GetString("Tubus_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sororibus.
        /// </summary>
        public static string Tubus_02 {
            get {
                return ResourceManager.GetString("Tubus_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavas.
        /// </summary>
        public static string Tubus_03 {
            get {
                return ResourceManager.GetString("Tubus_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosarium.
        /// </summary>
        public static string Tubus_04 {
            get {
                return ResourceManager.GetString("Tubus_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compagibus.
        /// </summary>
        public static string Tubus_05 {
            get {
                return ResourceManager.GetString("Tubus_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pennata.
        /// </summary>
        public static string Tussocks_01 {
            get {
                return ResourceManager.GetString("Tussocks_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventusa.
        /// </summary>
        public static string Tussocks_02 {
            get {
                return ResourceManager.GetString("Tussocks_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignis.
        /// </summary>
        public static string Tussocks_03 {
            get {
                return ResourceManager.GetString("Tussocks_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultro.
        /// </summary>
        public static string Tussocks_04 {
            get {
                return ResourceManager.GetString("Tussocks_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catena.
        /// </summary>
        public static string Tussocks_05 {
            get {
                return ResourceManager.GetString("Tussocks_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pennatis.
        /// </summary>
        public static string Tussocks_06 {
            get {
                return ResourceManager.GetString("Tussocks_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serrati.
        /// </summary>
        public static string Tussocks_07 {
            get {
                return ResourceManager.GetString("Tussocks_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albata.
        /// </summary>
        public static string Tussocks_08 {
            get {
                return ResourceManager.GetString("Tussocks_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagito.
        /// </summary>
        public static string Tussocks_09 {
            get {
                return ResourceManager.GetString("Tussocks_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisa.
        /// </summary>
        public static string Tussocks_10 {
            get {
                return ResourceManager.GetString("Tussocks_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caputus.
        /// </summary>
        public static string Tussocks_11 {
            get {
                return ResourceManager.GetString("Tussocks_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triticum.
        /// </summary>
        public static string Tussocks_12 {
            get {
                return ResourceManager.GetString("Tussocks_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stigmasis.
        /// </summary>
        public static string Tussocks_13 {
            get {
                return ResourceManager.GetString("Tussocks_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgam.
        /// </summary>
        public static string Tussocks_14 {
            get {
                return ResourceManager.GetString("Tussocks_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capillum.
        /// </summary>
        public static string Tussocks_15 {
            get {
                return ResourceManager.GetString("Tussocks_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string Vents {
            get {
                return ResourceManager.GetString("Vents", resourceCulture);
            }
        }
    }
}
