//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SignalSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignalSource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.SignalSource", typeof(SignalSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening Post.
        /// </summary>
        public static string ListeningPost {
            get {
                return ResourceManager.GetString("ListeningPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Extraction Site.
        /// </summary>
        public static string MULTIPLAYER_SCENARIO14_TITLE {
            get {
                return ResourceManager.GetString("MULTIPLAYER_SCENARIO14_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav Beacon.
        /// </summary>
        public static string MULTIPLAYER_SCENARIO42_TITLE {
            get {
                return ResourceManager.GetString("MULTIPLAYER_SCENARIO42_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Intensity Resource Extraction Site.
        /// </summary>
        public static string MULTIPLAYER_SCENARIO77_TITLE {
            get {
                return ResourceManager.GetString("MULTIPLAYER_SCENARIO77_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Intensity Resource Extraction Site.
        /// </summary>
        public static string MULTIPLAYER_SCENARIO78_TITLE {
            get {
                return ResourceManager.GetString("MULTIPLAYER_SCENARIO78_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous Resource Extraction Site.
        /// </summary>
        public static string MULTIPLAYER_SCENARIO79_TITLE {
            get {
                return ResourceManager.GetString("MULTIPLAYER_SCENARIO79_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compromised Nav Beacon.
        /// </summary>
        public static string MULTIPLAYER_SCENARIO80_TITLE {
            get {
                return ResourceManager.GetString("MULTIPLAYER_SCENARIO80_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered Comms Beacon.
        /// </summary>
        public static string NumberStation {
            get {
                return ResourceManager.GetString("NumberStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidentified Signal Source.
        /// </summary>
        public static string USS {
            get {
                return ResourceManager.GetString("USS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Aftermath.
        /// </summary>
        public static string USS_Type_Aftermath {
            get {
                return ResourceManager.GetString("USS_Type_Aftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomaly.
        /// </summary>
        public static string USS_Type_Anomaly {
            get {
                return ResourceManager.GetString("USS_Type_Anomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceremonial Comms.
        /// </summary>
        public static string USS_Type_Ceremonial {
            get {
                return ResourceManager.GetString("USS_Type_Ceremonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convoy Dispersal Pattern Detected.
        /// </summary>
        public static string USS_Type_Convoy {
            get {
                return ResourceManager.GetString("USS_Type_Convoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distress Call.
        /// </summary>
        public static string USS_Type_DistressSignal {
            get {
                return ResourceManager.GetString("USS_Type_DistressSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Target.
        /// </summary>
        public static string USS_Type_MissionTarget {
            get {
                return ResourceManager.GetString("USS_Type_MissionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Human Signal Source.
        /// </summary>
        public static string USS_Type_NonHuman {
            get {
                return ResourceManager.GetString("USS_Type_NonHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degraded Emissions.
        /// </summary>
        public static string USS_Type_Salvage {
            get {
                return ResourceManager.GetString("USS_Type_Salvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Beacon.
        /// </summary>
        public static string USS_Type_TradingBeacon {
            get {
                return ResourceManager.GetString("USS_Type_TradingBeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded Emissions.
        /// </summary>
        public static string USS_Type_ValuableSalvage {
            get {
                return ResourceManager.GetString("USS_Type_ValuableSalvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Grade Emissions.
        /// </summary>
        public static string USS_Type_VeryValuableSalvage {
            get {
                return ResourceManager.GetString("USS_Type_VeryValuableSalvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons Fire.
        /// </summary>
        public static string USS_Type_WeaponsFire {
            get {
                return ResourceManager.GetString("USS_Type_WeaponsFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Intensity Combat Zone.
        /// </summary>
        public static string Warzone_PointRace_High {
            get {
                return ResourceManager.GetString("Warzone_PointRace_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Intensity Combat Zone.
        /// </summary>
        public static string Warzone_PointRace_Low {
            get {
                return ResourceManager.GetString("Warzone_PointRace_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Intensity Combat Zone.
        /// </summary>
        public static string Warzone_PointRace_Med {
            get {
                return ResourceManager.GetString("Warzone_PointRace_Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AX Conflict Zone.
        /// </summary>
        public static string Warzone_TG {
            get {
                return ResourceManager.GetString("Warzone_TG", resourceCulture);
            }
        }
    }
}
