//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StationModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StationModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.StationModels", typeof(StationModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asteroid Base.
        /// </summary>
        public static string AsteroidBase {
            get {
                return ResourceManager.GetString("AsteroidBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocellus Starport.
        /// </summary>
        public static string Bernal {
            get {
                return ResourceManager.GetString("Bernal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coriolis Starport.
        /// </summary>
        public static string Coriolis {
            get {
                return ResourceManager.GetString("Coriolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Outpost.
        /// </summary>
        public static string CraterOutpost {
            get {
                return ResourceManager.GetString("CraterOutpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Port.
        /// </summary>
        public static string CraterPort {
            get {
                return ResourceManager.GetString("CraterPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megaship.
        /// </summary>
        public static string Megaship {
            get {
                return ResourceManager.GetString("Megaship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilian Megaship.
        /// </summary>
        public static string MegaShipCivilian {
            get {
                return ResourceManager.GetString("MegaShipCivilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Station.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbis Starport.
        /// </summary>
        public static string Orbis {
            get {
                return ResourceManager.GetString("Orbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outpost.
        /// </summary>
        public static string Outpost {
            get {
                return ResourceManager.GetString("Outpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Outpost.
        /// </summary>
        public static string OutpostScientific {
            get {
                return ResourceManager.GetString("OutpostScientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Station.
        /// </summary>
        public static string SurfaceStation {
            get {
                return ResourceManager.GetString("SurfaceStation", resourceCulture);
            }
        }
    }
}
