//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuitMod {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuitMod() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.SuitMod", typeof(SuitMod).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Movement Speed.
        /// </summary>
        public static string suit_adsmovementspeed {
            get {
                return ResourceManager.GetString("suit_adsmovementspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Backpack Capacity.
        /// </summary>
        public static string suit_backpackcapacity {
            get {
                return ResourceManager.GetString("suit_backpackcapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Resistance.
        /// </summary>
        public static string suit_improvedarmourrating {
            get {
                return ResourceManager.GetString("suit_improvedarmourrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Jump Assist.
        /// </summary>
        public static string suit_improvedjumpassist {
            get {
                return ResourceManager.GetString("suit_improvedjumpassist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced tracking.
        /// </summary>
        public static string suit_improvedradar {
            get {
                return ResourceManager.GetString("suit_improvedradar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Ammo Capacity.
        /// </summary>
        public static string suit_increasedammoreserves {
            get {
                return ResourceManager.GetString("suit_increasedammoreserves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Battery Capacity.
        /// </summary>
        public static string suit_increasedbatterycapacity {
            get {
                return ResourceManager.GetString("suit_increasedbatterycapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Melee Damage.
        /// </summary>
        public static string suit_increasedmeleedamage {
            get {
                return ResourceManager.GetString("suit_increasedmeleedamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased Air Reserves.
        /// </summary>
        public static string suit_increasedo2capacity {
            get {
                return ResourceManager.GetString("suit_increasedo2capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster Shield Regeneration.
        /// </summary>
        public static string suit_increasedshieldregen {
            get {
                return ResourceManager.GetString("suit_increasedshieldregen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased Sprint Duration.
        /// </summary>
        public static string suit_increasedsprintduration {
            get {
                return ResourceManager.GetString("suit_increasedsprintduration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Vision.
        /// </summary>
        public static string suit_nightvision {
            get {
                return ResourceManager.GetString("suit_nightvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quieter Footsteps.
        /// </summary>
        public static string suit_quieterfootsteps {
            get {
                return ResourceManager.GetString("suit_quieterfootsteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced Tool Battery Consumption.
        /// </summary>
        public static string suit_reducedtoolbatteryconsumption {
            get {
                return ResourceManager.GetString("suit_reducedtoolbatteryconsumption", resourceCulture);
            }
        }
    }
}
