//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDataDefinitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TradeRatings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TradeRatings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDataDefinitions.Properties.TradeRatings", typeof(TradeRatings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker.
        /// </summary>
        public static string Broker {
            get {
                return ResourceManager.GetString("Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        public static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite.
        /// </summary>
        public static string Elite {
            get {
                return ResourceManager.GetString("Elite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite 1.
        /// </summary>
        public static string EliteI {
            get {
                return ResourceManager.GetString("EliteI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite 2.
        /// </summary>
        public static string EliteII {
            get {
                return ResourceManager.GetString("EliteII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite 3.
        /// </summary>
        public static string EliteIII {
            get {
                return ResourceManager.GetString("EliteIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite 4.
        /// </summary>
        public static string EliteIV {
            get {
                return ResourceManager.GetString("EliteIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite 5.
        /// </summary>
        public static string EliteV {
            get {
                return ResourceManager.GetString("EliteV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneur.
        /// </summary>
        public static string Entrepreneur {
            get {
                return ResourceManager.GetString("Entrepreneur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string Merchant {
            get {
                return ResourceManager.GetString("Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly Penniless.
        /// </summary>
        public static string MostlyPenniless {
            get {
                return ResourceManager.GetString("MostlyPenniless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peddler.
        /// </summary>
        public static string Peddler {
            get {
                return ResourceManager.GetString("Peddler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penniless.
        /// </summary>
        public static string Penniless {
            get {
                return ResourceManager.GetString("Penniless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tycoon.
        /// </summary>
        public static string Tycoon {
            get {
                return ResourceManager.GetString("Tycoon", resourceCulture);
            }
        }
    }
}
